<?php include 'modules/help/assets/toc_include.php' ?>
<h3>Theme's Layout</h3>
<p>It is a good idea to check out Phil's template documentation. 
Bassically they are some variables you can use in your layout:
</p>
<ul>
	<li><b>$template['title']</b><br />This is generated by Phil's template</li>
	<li><b>$template['partials']['header']</b><br />Generated by header.php in the respective partial</li>
	<li><b>$template['partials']['footer']</b><br />Generated by footer.php in the respective partial</li>
	<li><b>$template['partials']['right']</b><br />Generated by right.php in the respective partial</li>
	<li><b>$template['partials']['left']</b><br />Generated by left.php in the respective partial</li>
	<li><b>$template['partials']['navigation_path']</b><br />Generated by navigation_path.php in the respective partial</li>
	<li><b>$template['body']</b><br />Your content</li>
	<li><b>$cms['site_name']</b><br />Site name from the configuration</li>
    <li><b>$cms['site_slogan']</b><br />Site slogan from the configuration</li>
    <li><b>$cms['site_footer']</b><br />Site footer from the configuration</li>
    <li><b>$cms['site_theme']</b><br />Site theme from the configuration</li>
    <li><b>$cms['site_logo']</b><br />Site logo from the configuration</li>
    <li><b>$cms['site_favicon']</b><br />Site favicon from the configuration</li>
    <li><b>$cms['navigations']</b><br />Navigations in array format, need some logic to show it in an appropriate way</li>
    <li><b>$cms['navigation_path']</b><br />Navigation path, need some logic to show it in an appropriate way</li>
    <li><b>$cms['widget']</b><br />Widget, need some logic to show it in an appropriate way</li>
    <li><b>$cms['user_name']</b><br />Current user name</li>
    <li><b>$cms['quicklinks']</b><br />Quick Links, need some logic to show it in an appropriate way</li>
    <li><b>$cms['module_name']</b><br />Current module name</li>			
</ul>
<p>The $cms variables can also be used in the partials as well
</p>
<p>This is an example default.php content:</p>
<pre class="htmlSnippet">
    &lt;html&gt;
	    &lt;head&gt;
	        &lt;title&gt;&lt;?php echo $template['title'];?&gt;&lt;/title&gt;
	        &lt;link rel="icon" href="&lt;?php echo $cms['site_favicon'];?&gt;"&gt;
	        &lt;script type="text/javascript" src ="&lt;?php echo base_url().'assets/nocms/js/jquery.js';?&gt;"&gt;&lt;/script&gt;
	        &lt;link rel="stylesheet" type="text/css" href="&lt;?php echo base_url()."themes/".$cms['site_theme']."/assets/default/style.css";?&gt;"&gt;&lt;/link&gt;
	        &lt;script type="text/javascript" src="&lt;?php echo base_url()."themes/".$cms['site_theme']."/assets/default/script.js";?&gt;"&gt;&lt;/script&gt;
	    &lt;/head&gt;
	    &lt;body&gt;       
	        
	        &lt;div id="layout_header"&gt;&lt;?php echo $template['partials']['header'];?&gt;&lt;/div&gt;
	        
	        &lt;div id="layout_center"&gt;
	            &lt;div id="layout_right"&gt;&lt;?php echo $template['partials']['right'] ?&gt;&lt;/div&gt;
	            &lt;div id="layout_content"&gt;
	                &lt;div id="layout_nav_path"&gt;You are here : &lt;?php echo $template['partials']['navigation_path']?&gt;&lt;/div&gt;
	                &lt;br /&gt;
	                &lt;?php echo $template['body'];?&gt;
	            &lt;/div&gt;
	            &lt;div class="layout_clear"&gt;&lt;/div&gt;
	        &lt;/div&gt;
	        
	        &lt;div id="layout_footer"&gt;&lt;?php echo $template['partials']['footer'];?&gt;&lt;/div&gt; 
	    &lt;/body&gt;
	&lt;/html&gt;
</pre>
<p>While this is an example header.php partials:</p>
<pre class="htmlSnippet">
    &lt;?php require_once BASEPATH."../themes/".$cms['site_theme']."/lib/function.php";?&gt;
	&lt;img class="layout_float_left" src ="&lt;?php echo $cms['site_logo'];?&gt;" /&gt;
    &lt;div class="layout_float_left layout_large_left_padding"&gt;
    	&lt;h1&gt;&lt;?php echo $cms['site_name'];?&gt;&lt;/h1&gt;
        &lt;h2&gt;&lt;?php echo $cms['site_slogan'];?&gt;&lt;/h2&gt;
        &lt;?php echo build_quicklink($cms['quicklinks']);?&gt;
    &lt;/div&gt;
    &lt;div class="layout_clear"&gt;&lt;/div&gt;
</pre>
<p>I hope you can get the idea :)</p>