INSERT INTO `cms_lib_book` (`id`, `isbn`, `title`, `author`, `publisher`, `description`) VALUES
(1, NULL, '10 Alasan Mengapa Saya Percaya bahwa Alkitab Firman Allah', 'William W. Orr', 'Kalam Hidup', NULL),
(2, NULL, '10 Hambatan terhadap Pertumbuhan', 'Tom Allen', 'Kalam Hidup', NULL),
(3, NULL, '10 Menit Menuju Sehat dengan Terapi Tulang Kepala Belakang ', 'Prof. H. M. Hembing Wijayakusuma ', 'Penerbit PT Gramedia Pustaka Utama', NULL),
(4, NULL, '100 Ide Efektif untuk Menerapkan disiplin Pada Anak Didik ', 'Sharon R. Berry, Ph. D ', 'Gloria Graffa', NULL),
(5, NULL, '100 jam Bersama Kitab Yesus ', 'Dr. Mervin E. Rosell ', 'Kalam Hidup', NULL),
(6, NULL, '100 Permenungan di Balik Terali Besi ', 'Richard Wurmbrand ', 'Yayasan Andi Yogyakarta', NULL),
(7, NULL, '101 Realitas', 'David R. Verrman', 'Kalam Hidup', NULL),
(8, NULL, '110 Ilustrasi Khotbah', 'Pdt. H. Soekahar', 'Gandum Mas', NULL),
(9, NULL, '110 Ilustrasi Khotbah ', 'PDt. H. Soekahar, B.Th. ', 'Penerbit Gandum Mas', NULL),
(10, NULL, '12 Ciri Kepemimpinan Yang Efektif ', 'LeRoy Eims', 'Kalam Hidup', NULL),
(11, NULL, '125 Ilustrasi Rohani', 'Andreas S. & T. Suharsono', 'Lembaga Literatur Babtis', NULL),
(12, NULL, '150 Kisah Jenaka dalam Alkitan ', 'Bernadette Mccarver Snyder ', 'Penerbit Kanisius', NULL),
(13, NULL, '25 Alasan Yang Menyebabkan Alkitab Itu Firman Allah ', 'Gordon Lindsay', '', NULL),
(14, NULL, '28 Hari Bermisi dengan Allah ', '', 'Mahasiswa Indonesia Menuai', NULL),
(15, NULL, '40 Cara Mengarahkan Anak ', 'Paul Lewis ', 'Kalam Hidup', NULL),
(16, NULL, '5 Kebutuhan Wanita', 'Dr. Gary & Barbara Rosberg', 'Indo Gracia', NULL),
(17, NULL, '5 Kunci Kebangunan Rohani di Kota anda ', 'Greg Crawford', 'Yayasan Andi Yogyakarta', NULL),
(18, NULL, '60 Permainan Rekreasi Segar ', 'PDt. H. Soekahar, B.Th. ', 'Penerbit Gandum Mas', NULL),
(19, NULL, '77 Permainan Asyik', 'Purnawan Kristanto', 'Andi', NULL),
(20, NULL, '77 Pertanyaan aktual mengenai seks, pacaran dan cinta', 'Ray E. Short', 'Kalam Hidup', NULL),
(21, NULL, 'A Grief Observed', 'C. S Lewis', 'Pionir Jaya', NULL),
(22, NULL, 'Ada Apa Dengan Pacaran Dan Seks', 'Pam Stenzel & Crystal Kirgiss', 'Yayasan Andi Yogyakarta', NULL),
(23, NULL, 'Agustinus', 'S. Djatimala', 'Gita Karya', NULL),
(24, NULL, 'Aids dan Perilaku Seksual', 'Ir. Herlianto', 'Kalam Hidup', NULL),
(25, NULL, 'Air Jang Hidup Uraian Tentang Indjil Markus ', 'P.S. Naipospos', 'BPK -GM', NULL),
(26, NULL, 'Ajarlah Kami Berdoa ', 'Graham Roberts ', 'BPK -GM', NULL),
(27, NULL, 'Ajat Jang Tepat (Ayat yang tepat)', 'L. Walter ', 'Badan Penerbit Kristen', NULL),
(28, NULL, 'Akal dan Kekristenan', 'Paul e. Little', 'Kalam Hidup', NULL),
(29, NULL, 'Akar Kesombongan ', 'Odniel Yedijah', 'Nafiri Gabriel', NULL),
(30, NULL, 'Akhir Zaman', 'Ir. Herlianto, M.Th', 'Yayasan Kalam Hidup', NULL),
(31, NULL, 'Aku Memilih Kristus ', 'Prof. Dr. O. Hallesby (Alm.)', 'Badan Penerbit Kristen', NULL),
(32, NULL, 'Aku Mentjari Tuhan', 'Isobel Kuhn ', 'Badan Penerbit Kristen', NULL),
(33, NULL, 'Aku Pernah Mati ', 'George G. Ritchie , diterjemahkan: S. Siregar ', 'BPK -GM', NULL),
(34, NULL, 'Aku Pertjaja', 'dr. J. Verkuyl ', 'Badan Penerbit Kristen', NULL),
(35, NULL, 'Aku Telah Mengakhiri Pertandingan Yang Baik ', 'In Memoriam Jerimia Rim ', 'Yayasan Andi Yogyakarta', NULL),
(36, NULL, 'Alam Roh ', 'Eku Hidayat', 'Bethlehem', NULL),
(37, NULL, 'Alkitab Dan Ilmu Pengetahuan ', 'Herlianto ', 'BPK -GM', NULL),
(38, NULL, 'Alkitab Dapat mengubah Hidup Anda', 'Marilyn Hickey', 'Immanuel', NULL),
(39, NULL, 'Alkitab Menjawab 100 Pertanyaan', 'OMF', 'BPK', NULL),
(40, NULL, 'Alkitab Menjawab 100 Pertanyaan (2)', 'diterjemahkan: MH. Simanungkalit', 'BPK -GM', NULL),
(41, NULL, 'Alkoholisme ', 'Dr. I. J. Cairns ', 'BPK -GM', NULL),
(42, NULL, 'Allah dalam Karya (INJIL MARKUS) ', 'Chuck & Winnie Christensen', 'Yayasan Gloria', NULL),
(43, NULL, 'Allah itu Berkuasa Tetapi Bagaimana?', 'Ds. P. B. Suurmond', 'BPK -GM', NULL),
(44, NULL, 'Allah Roh', 'Eku Hidayat', 'Bethlehem', NULL),
(45, NULL, 'Alpjonse Pelopor Muda: Riwajat Hidup Ephraim Alphonse dari Panama ', 'diterjemahkan: Barus Siregar ', 'Badan Penerbit Kristen', NULL),
(46, NULL, 'Amazing Grace ', 'John Newton', 'Penerbit Andi', NULL),
(47, NULL, 'Amsal Bahasa Sehari-hari', '', 'LAI', NULL),
(48, NULL, 'Anak dan Pola Perilakuannya ', 'Soerjono Soekanto S.H., M.A', 'BPK -GM', NULL),
(49, NULL, 'Anak-anak Yang Memerlukan Perhatian Khusus di Taman Kanak-kanak ', 'Lesley Webb', '', NULL),
(50, NULL, 'Anda Bertanya Billy Graham Menjawab (1) Masalah Hubungan Antarpribadi', '', 'Lembaga Literatur Babtis', NULL),
(51, NULL, 'Anda Karyawan Yang Baik ', '', 'Lembaga Alkitab Indonesia ', NULL),
(52, NULL, 'Anda sanggup mengatasi stres', 'Dr. Armand T. Fabela ', 'Indonesia Publishing House ', NULL),
(53, NULL, 'Aneh Tapi Nyata ', 'Pondsius & Susanna Takaliuang ', '', NULL),
(54, NULL, 'Anguished English ', 'Richard Lederer', 'Laurel', NULL),
(55, NULL, 'Ann H. Judson (Pahlawan Misi wanita di Birma)', 'E.R. Pitman ', 'YAKIN ', NULL),
(56, NULL, 'Apa yang Harus saya Lakukan? (Tanya Jawab Mengatasi kesulitan-kesulitan Remaja)', 'Drs. R. I. Suhartin', 'BPK -GM', NULL),
(57, NULL, 'Apakah Allah Mepercayai Anda', 'Keith R. Anderson', 'Kalam Hidup', NULL),
(58, NULL, 'Apresiasi Pilkada Kota Malang 2008-2013', '', 'Institut Pendidikan Theologia Balewijaya', NULL),
(59, NULL, 'Arsitek Jiwa II', 'Stephen Tong', 'Momentum', NULL),
(60, NULL, 'Asas-asas Alkitab bagi Kaum Muda', 'Raines & Richardson', 'Kalam Hidup', NULL),
(61, NULL, 'Awan Perak ', 'Betsy T. ', '', NULL),
(62, NULL, 'Ayub Sang Konglomerat', 'C. Bijl', 'Komunikasi Bina Kasih', NULL),
(63, NULL, 'Bagaimana Anda Menanggapi …Apologia Kristen dalam Doktrin Keselamatan ', 'Stefanus Theophilus, B. Th', 'PERKANTAS ', NULL),
(64, NULL, 'bagaimana berbicara dengan pasangan anda', 'H. Norman Wright', 'Kalam Hidup', NULL),
(65, NULL, 'Bagaimana bercakap=cakap dengan Anak ecil ', 'Rachel Iversen ', 'Kalam Hidup', NULL),
(66, NULL, 'Bagaimana Bergaul ', 'Jerry dan Mary White ', 'Kalam Hidup', NULL),
(67, NULL, 'Bagaimana Bersaat Teduh', 'Warren & Ruth Myers', 'Kalam Hidup', NULL),
(68, NULL, 'Bagaimana Bertahan bila Pekerjaan Menekan', 'Doug Sherman', 'Kalam Hidup', NULL),
(69, NULL, 'Bagaimana Dilahirkan Kembali ', 'Billy Graham ', 'Lembaga Literatur Babtis', NULL),
(70, NULL, 'Bagaimana Lepas Dari Jerat Godaan ', 'Tom L. Eisenman ', 'Gloria Graffa', NULL),
(71, NULL, 'Bagaimana Memahami Perjanjian Lama', 'Frank Michaeli', 'Kalam Hidup', NULL),
(72, NULL, 'Bagaimana Mengatasi Patah Semangat ', 'Rev. Armin R. Gesswein ', 'Kalam Hidup', NULL),
(73, NULL, 'Bagaimana Mengetahui Kehendak Allah', 'Charles Stanley ', 'Kalam Hidup', NULL),
(74, NULL, 'Bagaimana Menjadi Pemimpin pujian dan Pemimpin Acara (MC) yang Baik?', 'Ir. Mangapul Sagala, M. Div ', 'PERKANTAS ', NULL),
(75, NULL, 'Bagaimana Menjangkau Remaja', 'Ed Stewart', 'Kalam Hidup', NULL),
(76, NULL, 'Bagaimana Tokoh-tokoh Kristen', 'James C. Hefley', 'Kalam Hidup', NULL),
(77, NULL, 'Baptisan Roh Kudus', 'Ev. P. Ade Kolinus', 'Kalam Hidup', NULL),
(78, NULL, 'Be All You Can Be!', 'John C. Maxwell', 'Interaksara', NULL),
(79, NULL, 'Be Positive: Strategi Untuk Menghargai Diri Sendiri ', 'Joan Lloyd Guest ', 'Gloria Graffa', NULL),
(80, NULL, 'Bebas dari kesibukan ', 'Charles E. Hummel ', 'Gloria Graffa', NULL),
(81, NULL, 'Bebas dari Tujuh Dosa Maut ', 'Dr. Billy Graham', 'Yayasan Komunikasi Bina Kasih / OMF', NULL),
(82, NULL, 'Bebas Mengampuni ', 'David Augsburger', 'Kalam Hidup', NULL),
(83, NULL, 'Belajar Berdoa ', 'Hope McDonald, diterjemahkan: Fransisca Lestari ', 'BPK -GM', NULL),
(84, NULL, 'Benar Di Dalam Kristus', 'Warren W. Wiersbe', 'Yayasan Kalam Hidup', NULL),
(85, NULL, 'Benar Di Hadapan Allah', 'John Blanchard', 'Yayasan Kalam Hidup', NULL),
(86, NULL, 'Benih Mati memekar', 'Yong Choon Ahn', 'bpk', NULL),
(87, NULL, 'Berbahagia Menikah atau Membujang', 'Dr. Sam Kamaleson', 'Kalam Hidup', NULL),
(88, NULL, 'Berdoa', 'Bobb Biehl', 'Kalam Hidup', NULL),
(89, NULL, 'Berjalan Dari Timur Ke Barat', 'Ravi Zacharias', 'Pionir Jaya', NULL),
(90, NULL, 'Berkat yang Tercurah ', 'Ev. K. A. M. Jusuf Roni ', 'Yayasan Andi Yogyakarta', NULL),
(91, NULL, 'Berkemenangan Di Dalam Kristus', 'Warren W. Wiersbe', 'Kalam Hidup', NULL),
(92, NULL, 'Bermahasiswa', 'Dr. W.P Napitupulu', 'BPK', NULL),
(93, NULL, 'Berpacaran samapai dimana batasnya? ', 'Larry Richards, diterjemahkan: Sri Wandaningsih ', 'BPK -GM', NULL),
(94, NULL, 'Bersaksi  Dengan Mudah', 'C. S Lovett', 'Yayasan Kalam Hidup', NULL),
(95, NULL, 'Bersiap-siap di Dalam Kristus', 'Warren W. Wiersbe', 'Kalam Hidup', NULL),
(96, NULL, 'Bersyukur Itu Indah', 'Ayub Yahya', 'Gloria Graffa', NULL),
(97, NULL, 'Bertumbuh Menuju Kesempurnaan', 'Eddy Frances', 'Andi', NULL),
(98, NULL, 'Bila Kekasih Belum Percaya ', 'Alih bahasa: Jenny Natanael ', 'BPK -GM', NULL),
(99, NULL, 'Bila Orang Kristen Berdosa', 'John R. Rice', 'Kalam Hidup', NULL),
(100, NULL, 'Bila Orang Kristen Berdosa ', 'John R. Rice ', 'Kalam Hidup', NULL),
(101, NULL, 'Bila Percobaan Datang', 'John Osteen', 'Immanuel', NULL),
(102, NULL, 'Bila Tuhan Menyertai', 'Ny. Es. E. Maukary ', 'BPK -GM', NULL),
(103, NULL, 'Bill Graham Berwawancara dengan Kaum Muda', '', 'LLB', NULL),
(104, NULL, 'Bimbingan Berdasarkan Firman Allah', 'Martin & Deidre Bobgan', 'Kalam Hidup', NULL),
(105, NULL, 'Bolehkah Aku Percaya', 'Dorothy i. Marx', 'Kalam Hidup', NULL),
(106, NULL, 'Bukan Yesus Yang Saya Kenal (The Jesus I Never Knew)', 'Philip Yancey ', 'Professional Books', NULL),
(107, NULL, 'Buku Pintar Dunia Okultisme', 'Daud Tony', 'Bethlehem', NULL),
(108, NULL, 'Buku Pintar Konseling', 'Daud Tony', 'Bethlehem', NULL),
(109, NULL, 'Buku Pintar Konseling ', 'Selwyn Hughes', 'BETLEHEM ', NULL),
(110, NULL, 'Buku Pintar Konseling 2', 'Daud Tony', 'Bethlehem', NULL),
(111, NULL, 'Burung Berkicau ', 'Anthony De Mello SJ ', 'Yayasan Cipta Loka Caraka ', NULL),
(112, NULL, 'Cantik Dan Menarik ', 'Joyce Landorf ', 'Kalam Hidup', NULL),
(113, NULL, 'Cantik Dan Menarik ', 'Joyce Landorf ', 'Kalam Hidup', NULL),
(114, NULL, 'Cara melatih Murid Kristus', 'Walter A. Henrichsen', 'Kalam Hidup', NULL),
(115, NULL, 'Chlorella Makanan Sehat Alami ', 'Dr. David Steenblock, B.S., M.Sc., D.O', 'Penerbit PT Gramedia Pustaka Utama', NULL),
(116, NULL, 'Crazy Laws abridged from The Trenton Pickle Ordinance ', 'Dick Hyman', 'Scholastic Inc.', NULL),
(117, NULL, 'Cries of he Heart', 'Ravi Zacharias', 'Pionir Jaya', NULL),
(118, NULL, 'Damai dengan Allah ', 'Bily Graham ', 'Badan Penerbit Kristen', NULL),
(119, NULL, 'Dan Tuhan Tidak Bermain Dadu, Argumen Bagi Keterciptaan Alam Semesta ', 'Keith Ward ', 'Mizan Pustaka Kronik Zaman Baru ', NULL),
(120, NULL, 'Dapatkah Aku Dipakai Allah?', 'James Montgomery Boice ', 'Kalam Hidup', NULL),
(121, NULL, 'Dapatkan Yang Terbaik dari Tuhan ', 'Derek Prince ', 'Yayasan Duta Putera Mahkota ', NULL),
(122, NULL, 'Darah: Kuasanya dari Kejadian Sampai Yesus sampai Kepada Anda ', 'Benny Hinn', 'Yayasan Pekabaran Injil IMMANUEL', NULL),
(123, NULL, 'Dari Baptisan Roh Menuju Kepenuhan Roh', 'Homan Rubyono, M. A', 'Yayasan Kalam Hidup', NULL),
(124, NULL, 'Dari Betsaida Sampai Ke Yerusalem', 'Sostenis Nggebu, M. A', 'Kalam Hidup', NULL),
(125, NULL, 'Dari Kekuatiran Besar Sampai Sukacita Besar ', 'Hendra Rey dan Esther Junita ', 'STT Cipanas ', NULL),
(126, NULL, 'Dari Keraguan Hingga Percaya ', 'Rev. Andrew Song ', 'YAKIN ', NULL),
(127, NULL, 'Dari Mukjizat sampai Jelangkung', 'Arie Saptaji', 'Andi', NULL),
(128, NULL, 'Dari Taman Eden sampai Bait Allah', 'Sostenis Nggebu', 'Kalam Hidup', NULL),
(129, NULL, 'Dasar Iman Kepercayaan Kristen', 'Dr. Peter Wongso', 'SAAT', NULL),
(130, NULL, 'Dasar Kepercayaan Orang Kristen', 'Stewart Snook', 'Kalam Hidup', NULL),
(131, NULL, 'Dasar yang Teguh', 'J. Wesley Brill', 'Kalam Hidup', NULL),
(132, NULL, 'Datu Elka ', 'Homer E. Dowdy, diterjemahkan: Barus Siregar ', 'Badan Penerbit Kristen', NULL),
(133, NULL, 'Datu Elka - Kisah Pertobatan Seorang Dukun Di Amazone', 'Homer E. Dowdy, diterjemahkan: Barus Siregar ', 'BPK -GM', NULL),
(134, NULL, 'Daun Tanpa Ranting', 'Thomas T. Suharsono', 'Kalam Hidup', NULL),
(135, NULL, 'Delapan Tiang Keselamatan', 'Harold M. Freligh', 'Kalam Hidup', NULL),
(136, NULL, 'Dengan Doa kita Tempuh Perdjalanan kita Dalam Kehidupan ', 'Basilea Schlink', 'Tirta Amerta ', NULL),
(137, NULL, 'Derap Kuda Yang Sedang Mendekat ', 'Billy Graham ', 'Lembaga Literatur Babtis', NULL),
(138, NULL, 'Di Cari Pemimpin Yang Menjadi Pelayan', 'Gottfried Osei-Mensah', 'Yayasan Komunikasi Bina Kasih / OMF', NULL),
(139, NULL, 'Di Manakah Allah Saat Aku Menderita', 'Ayub Yahya', 'Gloria Graffa', NULL),
(140, NULL, 'Dihambat Tapi Merambat ', 'Ev. K. A. M. Jusuf Roni ', 'Yayasan Andi Yogyakarta', NULL),
(141, NULL, 'Dinamis Di dalam Kristus, Rasakan Kuasa Umat Allah ', 'Warren W. Wiersbe', 'Kalam Hidup', NULL),
(142, NULL, 'Diselamatkan secara Sempurna - Penggatian Hidup ', '', 'Penerbit Gandum Mas', NULL),
(143, NULL, 'Disini aku, Tuhan. Dimanakah Engkau? ', 'John M. Robertson ', 'BPK -GM', NULL),
(144, NULL, 'Diteguhkan Firman Hidup ', 'Robert E. Coleman', 'Yayasan Pekabaran Injil Nusantara', NULL),
(145, NULL, 'Djawab saja', 'Dr. Billy Graham', 'BPk', NULL),
(146, NULL, 'Doa ', 'Pdt. Biantoro Setijo ', 'Metanoia', NULL),
(147, NULL, 'Doa Mengalahkan Kemustahilan ', 'Jack Hayford ', 'Yayasan Andi Yogyakarta', NULL),
(148, NULL, 'Doa Menghasilkan Sejahtera', 'Kenneth E. Hagin', 'Faith Library Publication', NULL),
(149, NULL, 'Doa Muda Mudi ', 'William Barclay ', 'BPK -GM', NULL),
(150, NULL, 'Doa Yang Dikabulkan (Adventures In Prayer)', 'Catherine Marshall', 'BPK -GM', NULL),
(151, NULL, 'Doa-Doa Dalam Perjanjian Baru', 'J. Wesley Brill', 'Kalam Hidup', NULL),
(152, NULL, 'Doa-doa dalam Perjanjian Lama', 'J. Wesley Brill', 'Kalam Hidup', NULL),
(153, NULL, 'Doa-doa Setiap hari ', 'William Barclay ', 'BPK -GM', NULL),
(154, NULL, 'Dosa, Keadilan, dan Penghakiman ', 'Pdt. DR. Stephen Tong', 'Lembaga Reformed Injili Indonesia', NULL),
(155, NULL, 'Dr. Dobson Menjawab pertanyaan-pertanyaan mengenai: Memantapkan Kehidupan Keluarga ', 'James Dobson ', 'Kalam Hidup', NULL),
(156, NULL, 'Dukungan Bagi Kabar Baik Di Indonesia', '', 'LAI', NULL),
(157, NULL, 'Dunia Membongkar Ajaran Serangan Iblis Sesat', 'Daud Tony', 'Bethlehem', NULL),
(158, NULL, 'Dunia Roh', 'Mc Candlish Phillips', 'Kalam Hidup', NULL),
(159, NULL, 'Dunia Roh Teritorial', 'Daud Tony', 'Bethlehem', NULL),
(160, NULL, 'Dunia Wanita ', 'Ny. Andi ', 'Lembaga Literatur Babtis', NULL),
(161, NULL, 'Emosi Dapatkah Dipercaya ', 'Dr. James Dobson ', 'Penerbit Gandum Mas', NULL),
(162, NULL, 'Enam Sikap Bagi Para Pemenang ', 'Dr. Norman Vincent Peale', 'BPK -GM', NULL),
(163, NULL, 'Etika dan Pendidikan Seksual', 'Tulus Tu''u', 'Kalam Hidup', NULL),
(164, NULL, 'Etika Kristen dan Kebudayaan', 'dr. J. verkuyl', 'BPK', NULL),
(165, NULL, 'Etika Kristen Jilid II / 5 Kapita Selekta ', 'Dr. J. Verkuyl', 'BPK -GM', NULL),
(166, NULL, 'Etika Kristen Jilid II/1 Bag. Khusus Beberapa Masalah Etika Sosial-Ekonomis ', 'G.M.A Nainggolan ', 'BPK -GM', NULL),
(167, NULL, 'Evolusi atau Penciptaan', 'Prof. H. Enoch', 'Kalam Hidup', NULL),
(168, NULL, 'Gadis Pedjuang Iman ', 'Eric Gosden ', 'Badan Penerbit Kristen', NULL),
(169, NULL, 'Gadis Tjintaanku ', 'Walter Trobisch diterjemahkan: G.M.A. Nainggolan ', 'BPK -GM', NULL),
(170, NULL, 'Gembala Sidang Dan Pelayanannya', 'Seth Msweli & Donald Crider', 'Kalam Hidup', NULL),
(171, NULL, 'Gerak dan Canda: 74 Permainan untuk menyemarakkan kegiatan Gerejawi ', 'Calvyn Taunaumang, S.Th', 'Kalam Hidup', NULL),
(172, NULL, 'Grow In Grace ', 'Sinclair B. Ferguson ', 'Lembaga Reformed Injili Indonesia', NULL),
(173, NULL, 'Harga Menyerahkan Diri', 'John White ', 'Kalam Hidup', NULL),
(174, NULL, 'Haruskah Aku Bunuh Diri dan 7 kesaksian lainnya ', 'kesaksian dari: Naomi dkk', 'BPK -GM', NULL),
(175, NULL, 'Haruskah Sayang Mengampuni ', 'Goldie Bristol bersama Carol McGinnis ', 'Kalam Hidup', NULL),
(176, NULL, 'Hati Seorang Ibu', 'Jean Fleming', 'Yayasan Kalam Hidup', NULL),
(177, NULL, 'Hati Yang Terpanggil (Kumpulan Khotbah)', 'Ev. K. A. M. Jusuf Roni ', 'Yayasan Andi Yogyakarta', NULL),
(178, NULL, 'Heaven Is So Real', 'Choo Thomas', 'Creation House Press', NULL),
(179, NULL, 'Hendaklah Kamu Penuh dengan Roh Kudus', 'R.A. Torrey', 'Gandum Mas', NULL),
(180, NULL, 'Hendaklah Kamu Penuh dengan Roh Kudus ', 'R. A. Torrey ', 'Yayasan Penerbit Gandum Mas', NULL),
(181, NULL, 'Hidup dengan Allah - Rencana Allah Bagi Keluarga 9buku 3)', '', 'Kalam Hidup', NULL),
(182, NULL, 'Hidup Ini Indah', 'Ayub Yahya', 'Gloria Graffa', NULL),
(183, NULL, 'Hidup Itu Indah: Refleksi Theologi tentang Hidup melelui renungan dan tulisan ', 'Victor I. Tanja Ph. D', 'BPK -GM', NULL),
(184, NULL, 'Hidup Kudus?', 'Bob Hostetler', 'Kalam Hidup', NULL),
(185, NULL, 'Hikmat di Dalam Kristus Tafsiran I Korintus ', 'Warren W. Wiersbe', 'Kalam Hidup', NULL),
(186, NULL, 'Hukum Dosa, Hukum Maut dan Hukum Roh ', 'Pdt. Jusuf B.S ', 'Penerbit Bukit Zaitun ', NULL),
(187, NULL, 'Hukum Taurat Dan Kasih ', 'Harold H. Rowdon BA, Ph. D', 'Persekutuan Pembaca Alkitab (PPA)', NULL),
(188, NULL, 'Humanisme dan GZB', 'Ir. Herlianto', 'Kalam Hidup', NULL),
(189, NULL, 'Ia Dinamai Perempuan (1)', 'Gien Karssen ', 'Kalam Hidup', NULL),
(190, NULL, 'Ia Dinamai Perempuan (2)', 'Gien  Karssen ', 'Kalam Hidup', NULL),
(191, NULL, 'Ibadah Djemaat dalam Abad-abad Pertama ', 'Dr. J. L. Ch. Abineno ', 'Badan Penerbit Kristen', NULL),
(192, NULL, 'Ibu Yang Penuh Perhatian', 'Stephen & Janet Bly', 'Kalam Hidup', NULL),
(193, NULL, 'Iman yang Mengubah Situasi', 'K.A.M Jusuf Roni', 'Andi', NULL),
(194, NULL, 'Indahnya Pernikahan Kristen', 'Sutjipto Subeno', 'Momentum', NULL),
(195, NULL, 'Injil Markus', 'Marilyn Kunz', 'Kalam Hidup', NULL),
(196, NULL, 'Inovasi dan Visi Profetik dalam Pelayanan Kaum Muda', 'Mark Senter III', 'Yayasan Kalam Hidup', NULL),
(197, NULL, 'Intisari Iman Kristen ', 'Ds. Dr. B. J. Boland ', 'BPK -GM', NULL),
(198, NULL, 'Islamic Invation', 'Rovert Morey', 'Overseas Ministry', NULL),
(199, NULL, 'Istri Anda Rewel?', 'James Dobson', 'Kalam Hidup', NULL),
(200, NULL, 'Istri Yang Saleh', 'Leila Sparks ', 'Kalam Hidup', NULL),
(201, NULL, 'Itu ''Kan Boleh?', 'Dorothy i. Marx', 'Kalam Hidup', NULL),
(202, NULL, 'Jadilah Dirimu Yang Sebenarnya ', 'Larry Richards, diterjemahkan: Evang Darmaputera', 'BPK -GM', NULL),
(203, NULL, 'Jadilah Kuat ', 'Ev. K. A. M. Jusuf Roni ', 'Yayasan Andi Yogyakarta', NULL),
(204, NULL, 'Jadilah Kuat (IV)', 'Ev. K. A. M. Jusuf Roni ', 'Yayasan Andi Yogyakarta', NULL),
(205, NULL, 'Jalan Golgota', 'Roy Hession', 'Yakin', NULL),
(206, NULL, 'Jalanmu bukanlah Jalan-KU', '', 'Yayasan Andi Yogyakarta', NULL),
(207, NULL, 'Jaminan yang Pasti', 'H.A. Ironside', 'Kalam Hidup', NULL),
(208, NULL, 'Jangan Menyerah! Orang Kristen dan Penderitaan', 'Darmawan S. Bone ', 'Kalam Hidup', NULL),
(209, NULL, 'Janji Allah Untukmu ', 'Kathy Arbuckle ', 'Kalam Hidup', NULL),
(210, NULL, 'Janji-janji Alkitab', 'J. Stephen Lang', 'Kalam Hidup', NULL),
(211, NULL, 'Jatuh Cinta ', 'E. Tzer  Wong ', 'Yayasan Cipta Loka Caraka ', NULL),
(212, NULL, 'Jatuh Cinta Lagi ', 'David dan Carole Hocking ', 'Kalam Hidup', NULL),
(213, NULL, 'Jawab Saya', 'Dr. Billy Graham', 'BPK -GM', NULL),
(214, NULL, 'Jawaban Bagi Keraguan Anda', 'R. A. Torrey', 'Kalam Hidup', NULL),
(215, NULL, 'Jawaban bagi Pertanyaan Orang Yang Belum Percaya ', 'Josh McDowell dan Don Stewart', 'Penerbit Gandum Mas', NULL),
(216, NULL, 'Jesus Kristus Terang Dunia', '', 'Badan Penerbit Kristen', NULL),
(217, NULL, 'Jipertensi ', 'Vitahealth ', 'Penerbit PT Gramedia Pustaka Utama', NULL),
(218, NULL, 'JK', '', 'Kalam Hidup', NULL),
(219, NULL, 'John R. Mott', '', 'BPK', NULL),
(220, NULL, 'John Sung', 'Leslie T. Lyall', 'BPK -GM', NULL),
(221, NULL, 'Judi 200114', 'Pdt. Jusuf B.S ', '', NULL),
(222, NULL, 'Kagawa', 'William Axling', 'BPK -GM', NULL),
(223, NULL, 'Kalau Saudara Sakit', 'Nancy Nasution', 'BPK', NULL),
(224, NULL, 'Kamus Istilah Teologi ', 'Dr. R. Soedarmo ', 'BPK -GM', NULL),
(225, NULL, 'Karakter Kristen ', 'Andrea Sterk dan Peter Scazzero ', 'PERKANTAS ', NULL),
(226, NULL, 'Karunia-karunia Roh Dan Jemaat ', 'Donald Bridge dan David Phypers ', 'Kalam Hidup', NULL),
(227, NULL, 'Kata-kata Mutiara ', 'AMSAL ', 'Lembaga Alkitab Indonesia ', NULL),
(228, NULL, 'Katekismus Heidelberg', '', 'BPK', NULL),
(229, NULL, 'Kaum Injili Membangkitkan Kembali Iman Kristiani Ortodoks', 'Dr. Yakub B. Susabda ', 'Penerbit Gandum Mas', NULL),
(230, NULL, 'Kaya di Dalam Kristus ', 'Warren W. Wiersbe', 'Kalam Hidup', NULL),
(231, NULL, 'Ke Tempat yang Tinggi', 'Hannah Hurnard', 'Kalam Hidup', NULL),
(232, NULL, 'Kebahagiaan Sejati ', '', '', NULL),
(233, NULL, 'Kebenaran Sidang djumat ', 'Ds. Peter Wongso ', 'Madrasah Alkitab Asia Tenggara', NULL),
(234, NULL, 'Kebenaran Yang Memerdekakan', 'R. A. Torrey', 'Kalam Hidup', NULL),
(235, NULL, 'Kedaulatan dan Karya Kristus', 'John Stott', 'OMF', NULL),
(236, NULL, 'Kedewasaan Rohani ', 'J. Oswald Sanders ', 'Kalam Hidup', NULL),
(237, NULL, 'Kehendak Tuhan Bagiku', 'Wiharja Jian', 'Kalam Hidup', NULL),
(238, NULL, 'Kehidupan Kristen Yang Sukses', 'John Hunter', 'Yayasan Kalam Hidup', NULL),
(239, NULL, 'Kehidupan Sesudah Kematian', 'Pdt. Jusuf B.S ', '', NULL),
(240, NULL, 'Keindahan Yang Semu', 'Johanna Michaelsen', 'Kalam Hidup', NULL),
(241, NULL, 'Kejadian I', 'Hugh Ross, Ph. D', 'Kalam Hidup', NULL),
(242, NULL, 'Kekasihku Sebelum Pernikahan ', 'Dr. & Ny. Chong Kwong Tek dan Tn. & Ny. Chua Wee H', 'Lembaga Literatur Babtis', NULL),
(243, NULL, 'Kekasihku Setelah Pernikahan', 'Dr. y, Chong Kwong Tek dan Tn. & Ny. Chua Wee Hian', 'Lembaga Literatur Babtis', NULL),
(244, NULL, 'Kekhawatiran Itu Menghancyrkan - Belajar dari Kisah Saul - I Samuel 1 - 15', 'Pdt. Arliyanus Larosa, S. Th.', 'Kalam Hidup', NULL),
(245, NULL, 'Kekristenan Iman Yang Masuk Akal ', 'Dennis McCallum', 'Kalam Hidup', NULL),
(246, NULL, 'Kekuatan Dalam Kelemahan', 'Eric H. H. Chang', 'Yayasan Peduli Nusantara', NULL),
(247, NULL, 'Kekuatan Dalam Kelemahan', 'Jay Kesler ', 'Kalam Hidup', NULL),
(248, NULL, 'Kelompok Doa ', 'Dr. J. L. Ch. Abineno ', 'BPK -GM', NULL),
(249, NULL, 'Kelompok Sel Yang Berhasil ', 'Dr. Paul Cho Yonggi dan Harold Hostetler ', 'Penerbit Gandum Mas', NULL),
(250, NULL, 'Keluarga Kristen', 'Larry Christenson', 'Buku Betania', NULL),
(251, NULL, 'Keluarga yang Berdoa', 'Rosalind Rinker', 'Andi', NULL),
(252, NULL, 'Kemenangan Atas Derita ', 'Prof. William Goulooze', 'Badan Penerbit Kristen', NULL),
(253, NULL, 'Kenali Musuh Anda: Bagaiman Melawan dan Mengalahkan Kuasa-kuasa Kegelapan ', 'Norvel Hayes', 'Yayasan Perkabaran Injil IMMANUEL', NULL),
(254, NULL, 'Kenalilah Diri Anda', 'Dick Wulf', 'Gandum Mas', NULL),
(255, NULL, 'Kenyataan: Sungguh Terjadi Mujizat Allah Masa Kini ', 'Ibu Basilea Schlink ', 'Penerbit Gandum Mas', NULL),
(256, NULL, 'Kepemimpinan dalam Perspektif Alkitab', 'Eka Darmaputera', 'Kairos', NULL),
(257, NULL, 'Kepemimpinan Rohani  ', 'J. Oswald Sanders ', 'Kalam Hidup', NULL),
(258, NULL, 'Kepemimpinan Rohani dimulai di Rumah ', 'Tom Allen ', 'Kalam Hidup', NULL),
(259, NULL, 'Kepemimpinan yang Efektif', 'Bennie E. Goodwin', 'Perkantas', NULL),
(260, NULL, 'Kepemimpinan Yang Handal ', 'John White ', 'Kalam Hidup', NULL),
(261, NULL, 'Kepercayaan Orang Kristen ', '', 'YAKIN ', NULL),
(262, NULL, 'Keperluan Orang Luhur ', 'Witness Lee', 'Yayasan Perpustakaan Injil ', NULL),
(263, NULL, 'Kepertjajaan Kita ', 'Emil Brunner ', 'G. Kolff & Co. Bandung ', NULL),
(264, NULL, 'Kerika Seseorang berkata: Tolonglah saya! ', 'Everett L. Worthington, Jr. ', 'Kalam Hidup', NULL),
(265, NULL, 'Kesembuhan Emosi', 'David A. Seamands', 'Kalam Hidup', NULL),
(266, NULL, 'Kesembuhan Illahi Yang Diterima oleh Betty Baxter', 'Betty Baxter ', '', NULL),
(267, NULL, 'Kesembuhan Kasih Karunia ', 'david A. Seamands ', 'Kalam Hidup', NULL),
(268, NULL, 'Kesembuhan memori ', 'david A. Seamands ', 'Kalam Hidup', NULL),
(269, NULL, 'Kesimbangan Dalam Pelayanan Kristen ', 'Pdt. DR. Stephen Tong', 'YAKIN ', NULL),
(270, NULL, 'Kesulitan Pasti Berakhir ', 'Robert H. Schuller ', 'Interaksara', NULL),
(271, NULL, 'Ketaatan Yang Positif', 'John Bisagno', 'Kalam Hidup', NULL),
(272, NULL, 'Ketika Anak Anda Bertumbuh ', 'Margaret Bailey Jacobsen ', 'Kalam Hidup', NULL),
(273, NULL, 'Ketika Mukjizat Terjadi ', 'Lynne Hammond', 'Yayasan Andi Yogyakarta', NULL),
(274, NULL, 'Kewadjiban Hidup (Light On Life''s Duties)', 'F. B. Meyer ', 'YAKIN ', NULL),
(275, NULL, 'Kiat Menemukan Peluang dan Kepuasan Kerja Di Saat Krisis', 'Xavier Quentin Pranata ', 'Yayasan Andi Yogyakarta', NULL),
(276, NULL, 'Kisah Para Rasul', 'Irving L. Jensen', 'Kalam Hidup', NULL),
(277, NULL, 'Kisah Para Rasul: Buku Penuntun Belajar ', 'Irving L. Jensen', 'Kalam Hidup', NULL),
(278, NULL, 'Kisah Rasul-rasul', 'Dr. Barclay M. Newman', 'Kalam Hidup', NULL),
(279, NULL, 'Knowing God', 'J.I. Parker', 'Yayasan Andi Yogyakarta', NULL),
(280, NULL, 'Kompas Kehidupan Kristen', 'K. C. Hinckley', 'Kalam Hidup', NULL),
(281, NULL, 'Konseling yang Efektif dan Alkitabiah ', 'Larry Crabb', 'Yayasan Andi Yogyakarta', NULL),
(282, NULL, 'Krisis Di Tengah Baya ', 'Jim dan Sally Conway ', 'Kalam Hidup', NULL),
(283, NULL, 'Kristus Akan Datang Untuk yang Kedua Kalinya', 'Dr. R.A. Jaffray', 'Kalam Hidup', NULL),
(284, NULL, 'Kualami Kuasa Tuhan', '', 'Badan Penerbit Kristen', NULL),
(285, NULL, 'Kuasa Pengharapan', 'Merlin Carothers', 'Gandum Mas', NULL),
(286, NULL, 'Kuasa Ucapan', 'Tulus Tu''u', 'Kalam Hidup', NULL),
(287, NULL, 'Kupatuhi Perintah Tuhan', '', 'Badan Penerbit Kristen', NULL),
(288, NULL, 'Kutahu Yang Kupercaya', 'Paul e. Little', 'Kalam Hidup', NULL),
(289, NULL, 'Laki-laki Saleh ', 'R. Kent Hughes ', 'Kalam Hidup', NULL),
(290, NULL, 'Left Behind (1)', 'Jerry B. Jenkins - Tim LaHaye', 'Tyndale House Publishers', NULL),
(291, NULL, 'Left Behind (2)', 'Jerry B. Jenkins - Tim LaHaye', 'Tyndale House Publishers', NULL),
(292, NULL, 'Left Behind (3)', 'Jerry B. Jenkins - Tim LaHaye', 'Tyndale House Publishers', NULL),
(293, NULL, 'Left Behind (4)', 'Jerry B. Jenkins - Tim LaHaye', 'Tyndale House Publishers', NULL),
(294, NULL, 'Left Behind (5)', 'Jerry B. Jenkins - Tim LaHaye', 'Tyndale House Publishers', NULL),
(295, NULL, 'Left Behind (6)', 'Jerry B. Jenkins - Tim LaHaye', 'Tyndale House Publishers', NULL),
(296, NULL, 'Left Behind (7)', 'Jerry B. Jenkins - Tim LaHaye', 'Tyndale House Publishers', NULL),
(297, NULL, 'Left Behind (8)', 'Jerry B. Jenkins - Tim LaHaye', 'Tyndale House Publishers', NULL),
(298, NULL, 'Left Behind (9)', 'Jerry B. Jenkins - Tim LaHaye', 'Tyndale House Publishers', NULL),
(299, NULL, 'Lepas Dari Belenggu Yoga - Sebuah Kesaksian', 'Yan Solihin ', 'Kalam Hidup', NULL),
(300, NULL, 'Lika-Liku Seks No.2 ', 'Walter Trobisch, diterjemahkan: Ny. Piet Pattinasa', 'Yayasan Komunikasi Bina Kasih / OMF', NULL),
(301, NULL, 'Lonceng Kapel Tetap Berdentang ', 'Maria Antonia Sri Widyastuti', 'BPK -GM', NULL),
(302, NULL, 'Luka Batin', 'Ev. Agnes Maria', 'Maranatha Krista', NULL),
(303, NULL, 'Mahasiswa  Jang Bertanggung Djawab ', 'Dr. J. Verkuyl; Dr. Walter Lempp', 'BPK -GM', NULL),
(304, NULL, 'Mahasiswa Dan Kemahsiswaan', 'Drs. Supardan ', 'BPK -GM', NULL),
(305, NULL, 'Makan Dan Tetap Langsing ', 'Joyce Meyer ', 'Media Injil Kerajaan', NULL),
(306, NULL, 'Makanan Sehat ', 'dr. Kathleen H. Liwijayan-Kuntaraf ; Dr. Jonathan ', 'Indonesia Publishing House ', NULL),
(307, NULL, 'Makin Dipendam makin Menjerat', 'Karen Scalf Linamen', 'Kalam Hidup', NULL),
(308, NULL, 'Malaikat : Agen Rahasia Allah ', 'Billy Graham ', 'Lembaga Literatur Babtis', NULL),
(309, NULL, 'Malaikat di Sekitar Kita', 'Gary Kannaman', 'Yayasan Andi Yogyakarta', NULL),
(310, NULL, 'Mantapkan Keyakinan Anda ', 'Charles R. Swindoll', 'YAKIN ', NULL),
(311, NULL, 'Manusia Kain Kafan ', 'A. Widyamartaya', 'Penerbit Gandum Mas', NULL),
(312, NULL, 'Manusia Sukses', 'Pdt. Dr. Y. Tomatala', 'Penerbit Gandum Mas', NULL),
(313, NULL, 'Mari Berekreasi ', 'Dr. F. Ukur ', 'BPK -GM', NULL),
(314, NULL, 'Markus', 'Irving L. Jensen', 'Kalam Hidup', NULL),
(315, NULL, 'Markus', 'Irving L. Jensen', 'Yayasan Kalam Hidup', NULL),
(316, NULL, 'Masalah adalah Berkat ', 'Fengky M., S.E. ', 'Indonesia Galilea Ministries', NULL),
(317, NULL, 'Masalah Membesarkan Anak', 'James Dobson ', 'Kalam Hidup', NULL),
(318, NULL, 'Masalah-masalah dalam Rumah Tangga Kristen ', 'Jay E. Adams ', 'BPK -GM', NULL),
(319, NULL, 'Mata Air Yang Pahit ', 'Derek Prince ', 'Yayasan Pekabaran Injil IMMANUEL', NULL),
(320, NULL, 'Matius', 'Irving L. Jensen', 'Kalam Hidup', NULL),
(321, NULL, 'Melatih Pekerja Awam ', 'Byron W. Ross ', 'Kalam Hidup', NULL),
(322, NULL, 'Melawan Kuasa Kegelapan', 'Drs. Wilson Nadeak', 'Kalam Hidup', NULL),
(323, NULL, 'Melepas Belenggu Kekecewaan Dan Kehilangan', 'Pam Vredevelt', 'Gloria Graffa', NULL),
(324, NULL, 'Melepaskan diri dari Kebiasaan Buruk', 'Erwin W. Lutzer', 'Kalam Hidup', NULL),
(325, NULL, 'Melestarikan Perkawinan', '', 'Dahara Prize ', NULL),
(326, NULL, 'Melihat dengan Mata Iman ', 'Ev. K. A. M. Jusuf Roni ', 'Yayasan Andi Yogyakarta', NULL),
(327, NULL, 'Melihat ke dalam Perjanjian Lama Bag. Kedua ', 'Violet Exell, Eliud Sangu dan Jacky Riley', 'Kalam Hidup', NULL),
(328, NULL, 'Melihat ke dalam Perjanjian Lama bag. Keempat', 'Sani Banturi, Ernest, dan Freda Maxwell', 'Kalam Hidup', NULL),
(329, NULL, 'Melihat Ke Dalam Perjanjian Lama bag. Ketiga', 'L.M. Ammerman dan J. Maritim ', 'Kalam Hidup', NULL),
(330, NULL, 'Melihat ke dalam Perjanjian Lama bag. Pertama ', 'Peter Dominy ', 'Kalam Hidup', NULL),
(331, NULL, 'Memasarkan Gereja ', 'George Barna ', 'Kalam Hidup', NULL),
(332, NULL, 'Mematahkan Belenggu Homoseksualitas ', 'Frank Worthen ', 'Penerbit Gandum Mas', NULL),
(333, NULL, 'Membangun Harga Diri Anak Anda ', 'Gary Smalley dan John Trent, Ph. D', 'Kalam Hidup', NULL),
(334, NULL, 'Membangun Manusia Seutuhnya', 'Ev. K. A. M. Jusuf Roni ', 'Yayasan Andi Yogyakarta', NULL),
(335, NULL, 'membedah Politik Orde Baru ', 'Riswandha Imawan ', 'Pustaka Pelajar ', NULL),
(336, NULL, 'Membentuk Kelompok PA (penuntun untuk pemahaman Alkitab  Kelompok Kecil) ', '', 'Kalam Hidup', NULL),
(337, NULL, 'Membina Anak Bermoral', 'Don S. Otis', 'Yayasan Kalam Hidup', NULL),
(338, NULL, 'Membina Iman ', 'Andrew Murray ', 'Kalam Hidup', NULL),
(339, NULL, 'Membina Keluarga Bahagia ', 'K.A.M. Jusuf Roni ', 'Yayasan Andi Yogyakarta', NULL),
(340, NULL, 'Memenangkan Jiwa dengan Mudah ', 'C. S. Lovett, M.A., B. D, F. R. G. S. ', 'Kalam Hidup', NULL),
(341, NULL, 'Memenangkan Masa Depan ', 'Jack W. Hayford ', 'Yayasan Andi Yogyakarta', NULL),
(342, NULL, 'Memilih Pekerjaan Yang Cocok ', 'Cylde M. Narramore Ed. D', 'Kalam Hidup', NULL),
(343, NULL, 'Mempelajari Alkitab secara Praktis', 'Tim LaHaye', 'Kalam Hidup', NULL),
(344, NULL, 'Mempengaruhi Masyarakat -  Rencana Allah Bagi Keluarga (buku 4)', '', 'Kalam Hidup', NULL),
(345, NULL, 'Mempertahankan Kemurnian Gereja ', 'Pdt. Imanuel Noertjahyo Pribadi ', 'Kalam Hidup', NULL),
(346, NULL, 'memulai idup Baru ', '', 'Persekutuan Kristen Antar Universitas ', NULL),
(347, NULL, 'Memulihkan Hubungan yang Rusak', 'Ken Wilson', 'Kalam Hidup', NULL),
(348, NULL, 'Menaklukkan Segala Pikiran kepada Kristus', 'Richard L. Pratt', 'SAAT', NULL),
(349, NULL, 'Menang Atas Ajaran Sesat', 'Gilbert Lumoindong', 'Yayasan Andi Yogyakarta', NULL),
(350, NULL, 'Menang Atas Penderitaan ', 'Pdt. K.A.M. Jusuf Roni ', 'Yayasan Andi Yogyakarta', NULL),
(351, NULL, 'Menang Atas Penderitaan ', 'W. Bringham Hunter', 'Gloria Graffa', NULL),
(352, NULL, 'Menang Dengan Cara Allah ', 'Loren Cunningham & Janice Rogers ', 'Yayasan Andi Yogyakarta', NULL),
(353, NULL, 'Menang, Sukses, Berhasil ', 'Ev. K. A. M. Jusuf Roni ', 'Yayasan Andi Yogyakarta', NULL),
(354, NULL, 'Menanggalkan Perilaku Kekanak-kanakan ', 'david A. Seamands ', 'Kalam Hidup', NULL),
(355, NULL, 'Menciptakan Hubungan yang Romantis', 'Richard Strauss', 'Kalam Hidup', NULL),
(356, NULL, 'Mendekat Pada Allah', 'Kenneth Boa & Max Anders', 'Kalam Hidup', NULL),
(357, NULL, 'Mendengarkan Suaran Allah ', 'Peter Lord ', 'Nafiri Gabriel', NULL),
(358, NULL, 'Menemukan Allah dalam Badai Hidup ', 'Bill Hybels ', 'Gloria Graffa', NULL),
(359, NULL, 'Mengadakan Renungan Keluarga ', 'Clyde M. Narramore, Ed. D', 'Kalam Hidup', NULL),
(360, NULL, 'Mengambil Keputusan dalam Situasi Sulit ', 'Vance Havner ', 'Kalam Hidup', NULL),
(361, NULL, 'Mengapa Anak-anak Berkelakuan Buruk ', 'Bruce Narramore ', 'Kalam Hidup', NULL),
(362, NULL, 'Mengapa Khawatir', 'John Haggai', 'Kalam Hidup', NULL),
(363, NULL, 'Mengapa Takut Mencintai ', 'John Powell', 'Yayasan Cipta Loka Caraka ', NULL),
(364, NULL, 'Mengatasai Rasa Rendah Diri', 'Clyde M. Narramore, Ed. D', 'Kalam Hidup', NULL),
(365, NULL, 'Mengatasi Kesulitan-Kesulitan Dalam Pendidikan Anak', 'Drs. R.I Suhartin', 'BPK -GM', NULL),
(366, NULL, 'Mengatasi konflik Pernikahan ', 'Jack dan Carole Mayhall ', 'Kalam Hidup', NULL),
(367, NULL, 'Mengatasi Krisis Kehidupan', 'Creath Davis', 'Kalam Hidup', NULL),
(368, NULL, 'Mengatasi Masalah Hidup ', 'DR. Jonathan A. Trisna', 'Kalam Hidup', NULL),
(369, NULL, 'Mengatasi Pencobaan ', 'Don Baker ', 'Kalam Hidup', NULL),
(370, NULL, 'Mengatasi Rasa Depresi ', 'Clyde M. Narramore, Ed. D', 'Kalam Hidup', NULL),
(371, NULL, 'Mengenal Agam Kristen ', 'R. P. Chavan ', 'Kalam Hidup', NULL),
(372, NULL, 'Mengendalikan Lidah', 'Mark Kinzer', 'Kalam Hidup', NULL),
(373, NULL, 'Mengerti Kesembuhan Ilahi', 'Richard M. Sipley', 'Kalam Hidup', NULL),
(374, NULL, 'Mengerti Tingkah Laku Anak Anda', 'Beverly Lahaye', 'Kalam Hidup', NULL),
(375, NULL, 'Menggembalakan Anak Anda', 'Tedd Tripp', 'Gandum Mas', NULL),
(376, NULL, 'Menghibur Lara, Menyembuhkan Duka ', 'Sara Wengerd', 'Gloria Graffa', NULL),
(377, NULL, 'Mengikut Yesus', 'Jack Selfridge', 'Kalam Hidup', NULL),
(378, NULL, 'Mengikut Yesus ', 'Dietrich Bonhoeffer', 'BPK -GM', NULL),
(379, NULL, 'Mengikuti Pimpinan Roh', 'Dr. A.B. Simpson', 'Kalam Hidup', NULL),
(380, NULL, 'Mengkritik dan Dikritik', 'John W. Alexander', 'Kalam Hidup', NULL),
(381, NULL, 'Menikah Itu Gampang?', 'Drs. Wilson Nadeak ', 'Kalam Hidup', NULL),
(382, NULL, 'Menikmati Alkitab', 'Irving L. Jensen', 'Kalam Hidup', NULL),
(383, NULL, 'Menjadi Bahagia (The Rare Jewel of Christian Contentment)', 'Jeremiah Burroughs', 'Yayasan Gloria', NULL),
(384, NULL, 'Menjadi dan Menjadikan Murid Kristus', 'Carol Fish', 'Kalam Hidup', NULL),
(385, NULL, 'Menjadi Guru Profesional', 'B.S. Sidjabat', 'Kalam Hidup', NULL),
(386, NULL, 'Menjadi Milik Allah ', 'Rachel Heartfield ', 'Kalam Hidup', NULL),
(387, NULL, 'Menjadi Pekerja Kristus', 'Tom Yeakley', 'Yayasan Kalam Hidup', NULL),
(388, NULL, 'Menjadi Pelayan Kristus', 'Dr. T. Haryono', 'PMK Surakarta', NULL),
(389, NULL, 'Menjadi Pelayan Kristus ', 'Pdt. DR. Stephen Tong', 'YAKIN ', NULL),
(390, NULL, 'Menjangkau Dunia Melalui Doa', 'Wesley L. Duewel', 'Kalam Hidup', NULL),
(391, NULL, 'Menolong Anak Anda bertumbuh dalam IMAN ', 'Clyde M. Narramore, Ed. D', 'Kalam Hidup', NULL),
(392, NULL, 'Menolong Anak Korban Perceraian ', 'Dr. Archibald D. art ', 'Kalam Hidup', NULL),
(393, NULL, 'Menyangkal Yesus atau Ditembak Mati', 'kesaksian', 'BPK', NULL),
(394, NULL, 'Menyesuaikan Diri dengan Orang Lain ', 'Larry Richards, alih bahasa: Fransisca Lestari ', 'BPK -GM', NULL),
(395, NULL, 'Menyingkap Tabir Tai Chi & Wai Tan Kung ', 'Ir. Herlianto, M.Th', 'Yayasan Andi Yogyakarta', NULL),
(396, NULL, 'Menyongsong Peperangan ', 'Robertsn Liardon', 'Yayasan Pekabaran Injil IMMANUEL', NULL),
(397, NULL, 'Merdeka di Dalam Kristus ', 'Warren W. Wiersbe', 'Kalam Hidup', NULL),
(398, NULL, 'Mereka Akan Mengusir Setan-setan ', 'Derek Prince ', 'Derek Prince Ministries Indonesia ', NULL),
(399, NULL, 'Meringankan Derita Orang Tua ', 'Mary Rae Deatrick', 'Penerbit Gandum Mas', NULL),
(400, NULL, 'Meski Gentar Tetap Tegar - Ekposisi Kitab Habakuk ', 'D. Martyn Llioyd Jones ', 'PERKANTAS ', NULL),
(401, NULL, 'Metode Penelaahan Alkitab ', 'Dick dan Tinem Maitimoe', 'Persekutuan Pembaca Alkitab (PPA)', NULL),
(402, NULL, 'Misi Sosial Gereja', 'Pdt. Arliyanus Larosa', 'Kalam Hidup', NULL),
(403, NULL, 'Misteri Iblis', 'William W. Orr', 'Yayasan Kalam Hidup', NULL),
(404, NULL, 'Misteri Iblis ', 'William W. Orr `', 'Kalam Hidup', NULL),
(405, NULL, 'Mujizat Masih Berlangsung ', 'Kathryn Kuhlman ', 'Penerbit Gandum Mas', NULL),
(406, NULL, 'Mujizat Terjadi Bila Wanita Berdoa ', 'Evelyn Christenson bersama Viola Blake ', 'Penerbit Gandum Mas', NULL),
(407, NULL, 'Murid Sejati', 'Paul W. Powell', 'Yayasan Kalam Hidup', NULL),
(408, NULL, 'Murid-Murid Kristus dibuat Bukan Dilahirkan ', 'Walter A. Henrichsen ', 'Kalam Hidup', NULL),
(409, NULL, 'Ngegosip', 'Mark Littleton', 'Kalam Hidup', NULL),
(410, NULL, 'Nyata di dalam Kristus ', 'Warren W. Wiersbe', 'Kalam Hidup', NULL),
(411, NULL, 'Orang Kristen dalam Masa Transisi ', 'William J. Murray ', 'Kalam Hidup', NULL),
(412, NULL, 'Orang Kristen Duniawi', 'Rich Wilkerson', 'Kalam Hidup', NULL),
(413, NULL, 'Orang Kristen yang Dipenuhi Roh Kudus ', '', 'Kalam Hidup', NULL),
(414, NULL, 'Orang Pedalaman ', 'Matia Madjiah ', 'BPK -GM', NULL),
(415, NULL, 'Orang Tua, Berbicaralah dengan anak-anak', 'V. Gilbert Beers', 'Kalam Hidup', NULL),
(416, NULL, 'Orang yang Dipakai oleh Allah', 'Dr. Oswald J. Smith', 'Christian Literarur Crusade', NULL),
(417, NULL, 'Orang-orang Yang Berbahagia ', 'Pdt. Ichwei G. Indra ', 'Kalam Hidup', NULL),
(418, NULL, 'Pandangan Agama Kristen tentang New Morality ', 'Dorothy i. Marx', 'Kalam Hidup', NULL),
(419, NULL, 'Panduan Praktis Penerapan The Purpose Driven Life ', 'S. Christian Robirosa', 'Yayasan Andi Yogyakarta', NULL),
(420, NULL, 'Pedoman Apologetik Kristen 1', 'Peter Kreeft& Ronald K. Tacelli', 'Kalam Hidup', NULL),
(421, NULL, 'Pedoman Apologetik Kristen 2', 'Peter Kreeft& Ronald K. Tacelli', 'Kalam Hidup', NULL),
(422, NULL, 'Pedoman Lengkap Nubuat Alkitan ', 'John F. Walvoord ', 'Kalam Hidup', NULL),
(423, NULL, 'Pedoman Lengkap Untuk Pelayanan  Kaum Muda', 'Warren S. Benson & Mark H. Senter III', 'Kalam Hidup', NULL),
(424, NULL, 'Pedoman Lengkap Untuk Pelayanan  Kaum Muda (I)', 'Warren S. Benson & Mark H. Senter III', 'Kalam Hidup', NULL),
(425, NULL, 'Pedoman Mentjari Kehendak Allah', 'G. Christian Weiss', 'Yakin', NULL),
(426, NULL, 'Pedoman Pembinaan Warga Jemaat ', 'Dr. Ruth F. Selan ', 'kalan', NULL),
(427, NULL, 'Pedoman Pemuridan ', 'Doug Hartman dan Doug Sutherland ', 'Kalam Hidup', NULL),
(428, NULL, 'Pedoman Perkawinan', 'GKII', 'Kalam Hidup', NULL),
(429, NULL, 'Pedoman Persekutuan Kaum wanita (Perkawan) ', 'Gereja Kemah Injil Indonesia ', 'Kalam Hidup', NULL),
(430, NULL, 'Pedoman Pertemuan Perkawan (2) ', '', 'Kalam Hidup', NULL),
(431, NULL, 'Pedoman Pokok-pokok Isi Alkitab ', '', 'Kalam Hidup', NULL),
(432, NULL, 'Pedoman Upacara Kristisani ', '', 'Kalam Hidup', NULL),
(433, NULL, 'Pekerja Kristus', 'Watchman Nee', 'Kalam Hidup', NULL),
(434, NULL, 'Pekerjaan Anda Penting Bagi Allah', 'Dough Sherman', 'Kalam Hidup', NULL),
(435, NULL, 'Pelajanan dan Peljan Djemaat dalam Perdjandjian Baru ', 'Dr. J. L. Ch. Abineno ', '', NULL),
(436, NULL, 'Pelayanan Makanan Sehat ', 'Ellen G. White ', 'Indonesia Publishing House ', NULL),
(437, NULL, 'Pelurusan Teologi Akhir Zaman', 'W. Stanley Heath', 'Kalam Hidup', NULL),
(438, NULL, 'Pembangun & Orang Bodoh', 'Derek J. Tidball', 'Kalam Hidup', NULL),
(439, NULL, 'Pembelaku Yang Agung ', 'Abubakar Masyur Jusuf Roni ', 'Lembaga Pelayanan Jusuf Roni', NULL),
(440, NULL, 'Pemberitaan Injil Tugas Siapa?', 'Paul Borthwick', 'Kalam Hidup', NULL),
(441, NULL, 'Pembimbing ke dalam Ilmu Filsafat', '', '', NULL),
(442, NULL, 'Pemecahan Problema Hidup ', 'Dr. Paul Yonggi Cho ', 'Penerbit Gandum Mas', NULL),
(443, NULL, 'Pemenang dan Pecundang', 'Stephen dan Janet', 'Kalam Hidup', NULL),
(444, NULL, 'Pemuda dan Krisis Zaman ', 'Pdt. DR. Stephen Tong', 'Stephen Rong Evangelistic Ministries International', NULL),
(445, NULL, 'Pemulihan dari Disfungsi Keluarga ', 'Dale & Juanita Ryan ', 'seminari Alkitab Asia Tenggara ', NULL),
(446, NULL, 'Pemulihan dari Kehilangan', 'Dale & Juanita Ryan', 'SAAT', NULL),
(447, NULL, 'Pendidikan Agama Kristen Untuk Anak-Anak ', 'Mildred Proctor', 'Badan Penerbit Kristen', NULL),
(448, NULL, 'Pendidikan Kehidupan Keluarga ', 'Ny. S. Soekamto', 'BPK -GM', NULL),
(449, NULL, 'Pendidikan Seks dari Orang Tua kepada Anak', 'Mary Ann Mayo', 'Kalam Hidup', NULL),
(450, NULL, 'Pengantar Penjanjian Baru', 'Adina Chapman', 'Kalam Hidup', NULL),
(451, NULL, 'Pengantar Riset Kuantitatif dan Kualitatif ', 'Andreas B. Subagyo, Ph. D.', 'Kalam Hidup', NULL),
(452, NULL, 'Pengantar Teologia Kristen', 'Daniel Lukas Lukito', 'Kalam Hidup', NULL),
(453, NULL, 'Penggembalaan ', 'Dr. J. L. Ch. Abineno ', 'Badan Penerbit Kristen', NULL),
(454, NULL, 'Penggenapan Janji Allah', 'Hal Lindsey', 'Kalam Hidup', NULL),
(455, NULL, 'Pengharapan Di Dalam Kristus ', 'Werren W. Wiersbe ', 'Kalam Hidup', NULL),
(456, NULL, 'Penghiburan yang Menguatkan ', 'Lauren Briggs ', 'Kalam Hidup', NULL),
(457, NULL, 'Penghidupan Orang Kristen Yang Normal ', 'Watchman Nee ', 'Yayasan Perpustakaan Injil ', NULL),
(458, NULL, 'Penguasa-penguasa Bumi ', 'Don Richardson ', 'Kalam Hidup', NULL),
(459, NULL, 'Penting dan Genting ', 'DR. Don L. Fisher, MA', 'Penerbit Gandum Mas', NULL),
(460, NULL, 'Penuai Yang Diperlengkapi ', 'LeRoy Eims', 'Penerbit Gandum Mas', NULL),
(461, NULL, 'Penuntun Kedalam Perdjanjian Lama ', 'Henry H. Halley ', 'YAKIN ', NULL),
(462, NULL, 'Penuntun Sekolah Minggu', 'J. Reginald Hill', 'OMF', NULL),
(463, NULL, 'Penyelidikan Alkitab secara Induktif', 'Marge Fuller', 'Kalam Hidup', NULL),
(464, NULL, 'Penyelidikan Perjanjian Baru ', 'Ephraim Moalusi, Stewart Snook, Richard Jordahl', 'Kalam Hidup', NULL),
(465, NULL, 'Penyelidikan Perjanjian Baru Bag. Ketiga - 1 Timotius sampai Wahyu ', 'E. Chauke dan B. Beckelhymer ', 'Kalam Hidup', NULL),
(466, NULL, 'Penyelidikan Perjanjian Baru Bag. Pertama - Matius sampai Kisah Para Rasul ', 'Alpheus Khumalo, Ephraim Moalusi, Stewart Snook ', 'Kalam Hidup', NULL),
(467, NULL, 'People Helpers Ministry Indonesia', 'Pdt. Yakub B. Susabda, Ph. D', 'People Helpers Ministry Indonesia', NULL),
(468, NULL, 'Peranan Roh Kudus', 'W. Curry Mavis', 'Penerbit Gandum Mas', NULL),
(469, NULL, 'Perang Melawan Sihir ', 'Gilbert Lumoindong ', 'BETLEHEM ', NULL),
(470, NULL, 'Percaya Kepada Allah ', 'Rachel Heartfield ', 'Kalam Hidup', NULL),
(471, NULL, 'Perencana dan Pemimpi ', 'Luis Palau ', 'YAKIN ', NULL),
(472, NULL, 'Pergumulan Seorang Homoseks', 'Nancy ', 'Kalam Hidup', NULL),
(473, NULL, 'Perkawinan Jang Bahagia ', 'Gertrude Nystrom', 'yaki]', NULL),
(474, NULL, 'Pernikahan Dan Seksualitas', 'James Dobson', 'Kalam Hidup', NULL),
(475, NULL, 'Pernikahan Yang Intim', 'David & Carole Hocking', 'Kalam Hidup', NULL),
(476, NULL, 'Persamaan Ayat-Ayat Keempat Injil ', 'Dr. R. A. Jaffray ', 'Kalam Hidup', NULL),
(477, NULL, 'Persembahan yang Baik dan Benar dari Tuhan untuk Tuhan ', 'wiharja Jian ', 'Kalam Hidup', NULL),
(478, NULL, 'Persiapan Hari Pernikahan ', 'Eric dan Paula Burtness ', 'Kalam Hidup', NULL),
(479, NULL, 'Pertanyaan yang Sulit akan dijawab oleh Luis Palan ', 'Luis Palan ', 'Lembaga Literatur Babtis', NULL),
(480, NULL, 'Pertolongan Di tengah badai ', 'Ev. K. A. M. Jusuf Roni ', 'Yayasan Andi Yogyakarta', NULL),
(481, NULL, 'Pertolongan Tuhan atas Persoalan Saya', '', 'BPK', NULL),
(482, NULL, 'Pertolongan Tuhan atas Persoalan Saya', 'J. Dwight Pentecost', 'BPK -GM', NULL),
(483, NULL, 'Pertolonganku Ialah dari Tuhan ', 'Lukas Eko Sukoco ', 'Yayasan Andi Yogyakarta', NULL),
(484, NULL, 'Pertukaran Pada Kayu Salib ', 'Derek Prince ', 'Yayasan Pekabaran Injil IMMANUEL', NULL),
(485, NULL, 'Perumpamaan Tuhan Yesus', 'Dr. R.A. Jaffray', 'Kalam Hidup', NULL),
(486, NULL, 'Prajurit Peperangan Rohani', 'Daud Tony', 'Bethlehem', NULL),
(487, NULL, 'Praktek dan Strategi Iblis', 'Pdr. John M. Gobay', 'Kalam Hidup', NULL),
(488, NULL, 'Praktik Iman ', 'Drs. Irwan Halim', 'Kalam Hidup', NULL),
(489, NULL, 'Pria Paruh Baya', 'James A. Harnis', 'Kalam Hidup', NULL),
(490, NULL, 'Prioritas Utama dalam Penyembahan', 'John MacArthur', 'Kalam Hidup', NULL),
(491, NULL, 'Proyek-Proyek Khusus LAI', '', 'LAI', NULL),
(492, NULL, 'Psikologi dan Alkitab ', 'Larry Richards ', 'Kalam Hidup', NULL),
(493, NULL, 'PUASA ', 'James Lee Beall ', 'Kalam Hidup', NULL),
(494, NULL, 'Quality of Life', 'Eric H.H. Chang', 'Yayasan Peduli Nusantara', NULL),
(495, NULL, 'Quality Of Life (Rahasia Hidup) ', 'Eric H. H. Chang', 'Cahaya Pengharapan Ministries', NULL),
(496, NULL, 'Rahasia Berhasilnja Kehidupan Kristen', 'R.A. Torrey', 'Christian Literarur Crusade', NULL),
(497, NULL, 'Rahasia Di Balik Astrologi', 'Charles Strohmer', 'Kalam Hidup', NULL),
(498, NULL, 'Rahasia Hidup Bahagia ', 'Billy Graham ', 'Lembaga Literatur Babtis', NULL),
(499, NULL, 'Rahasia Holly', 'Lynn Stanley', 'Kalam Hidup', NULL),
(500, NULL, 'Rahasia Kehidupan Kristen Yang Bahagia ', 'Hannah Whitall Smith ', 'Kalam Hidup', NULL),
(501, NULL, 'Rahasia Penginjil Api', 'Daud Tony', 'Bethlehem', NULL),
(502, NULL, 'Rahasia Untuk Bertahan Hidup', 'dr. Susan B. Anthony', '', NULL),
(503, NULL, 'Raising Kids to Love Jesus 2 ', 'H. Norman Wright; Gary J. Oliver ', 'Gloria Graffa', NULL),
(504, NULL, 'Rasakan Kebaikan Allah ', 'Barry Applewhite', 'Kalam Hidup', NULL),
(505, NULL, 'Reainkarnasi ', 'Norman L. Geisler & J. Yutaka Amano', 'Penerbit Gandum Mas', NULL),
(506, NULL, 'Rencana Agung Penginjilan', 'Robert E. Coleman', 'Kalam Hidup', NULL),
(507, NULL, 'Rencana Allah Bagi Rumah Tangga Kristen', 'Joyce Coon, Isaac, & Margaret Simbiri', 'Kalam Hidup', NULL),
(508, NULL, 'Renungan Untuk Kaum Wanita ', 'L. F. Marsh & M. E. Kemp ', 'Kalam Hidup', NULL),
(509, NULL, 'Respectable Sins', 'Jerry Bridges', 'Pionir Jaya', NULL),
(510, NULL, 'Riwajat Hidup D. L. Moody ', 'A.P. Fitt', 'N.V. Ching Nien', NULL),
(511, NULL, 'Riwajat Hidup Sadhu Sundar Singh', 'C. F. Andrews ', '', NULL),
(512, NULL, 'Roh Kudus! Penuhilah Aku! ', 'Fred Hartley ', 'Kalam Hidup', NULL),
(513, NULL, 'Sabda dalam Kata ', 'Andreas B. Subabyo', 'Kalam Hidup', NULL),
(514, NULL, 'Sains Iman dan Teknologi', 'W. Stanley Heath', 'Yayasan Andi Yogyakarta', NULL),
(515, NULL, 'Saksi Yehuwa', 'Ir. Herlianto', 'Kalam Hidup', NULL),
(516, NULL, 'Salib Yesus', 'Leon Morris', 'SAAT', NULL),
(517, NULL, 'Saling Mengbangun', 'Gene A. Getz', 'Kalam Hidup', NULL),
(518, NULL, 'Sandi Patti LeVoyage ', 'Bob farell dan Greg Nelson ', 'Word Publishing', NULL),
(519, NULL, 'Santun dalam Cerita ', 'Dra. Magdalena Sukartono', 'Yayasan Andi Yogyakarta', NULL),
(520, NULL, 'Segarkan Kembali Pelayanan Anda', 'Paul Borthwick', 'Andi', NULL),
(521, NULL, 'Sehat Rohani Sehat Jasmani', 'Harold Paul Adolph, M. D', 'Kalam Hidup', NULL),
(522, NULL, 'sehatkah Lidah Anda ', 'Derek Prince ', 'Yayasan Pekabaran Injil IMMANUEL', NULL),
(523, NULL, 'Sejenak  di Alam Baka (My Glimpse of Eternity)', 'Betty Malz ', 'BPK -GM', NULL),
(524, NULL, 'Selangkah Lebih Maju ', 'Joni Eareckson bersama Joe Musser', 'Penerbit Gandum Mas', NULL),
(525, NULL, 'Sendirian dengan Allah', 'Suhandhy Susantio', 'Kalam Hidup', NULL),
(526, NULL, 'Sendirian, Namun Tidak Kesepian', 'kesaksian', 'BPK', NULL),
(527, NULL, 'Sendirian, Namun Tidak Kesepian dan 6 kesaksian lainnya ', 'kesaksian dari: Maria Folla dkk', 'BPK -GM', NULL),
(528, NULL, 'Seni Manajemen bagi Pemimpin Kristen', 'Ted W. Engstrom', 'Kalam Hidup', NULL),
(529, NULL, 'Seni Membentuk Karakter Kristen', 'Dr. Mary Setiawani & Pdt. DR. Stephen Tong', 'Momentum', NULL),
(530, NULL, 'Senyum Sana sini ', 'Harsono Kelop & Andreas Sudarsono ', 'Lembaga Literatur Babtis', NULL),
(531, NULL, 'Setan Ada atau Tidak?', 'William W. Orr', 'Kalam Hidup', NULL),
(532, NULL, 'Setia di dalam Kristus - Tafsiran I dan II Korintus, dan Titus ', 'Warren W. Wiersbe', 'Kalam Hidup', NULL),
(533, NULL, 'Setia Sampai Mati (Cerita tentang Penindasan dan Pembunuhan atas orang-orang Kristen Malagasi)', 'H. A. Oppusunggu', 'BPK -GM', NULL),
(534, NULL, 'Setiap Langkah adalah Anugerah', 'Eddy Nugroho', 'Gloria Graffa', NULL),
(535, NULL, 'Siap Tempur', 'Mark R. Littleton', 'Kalam Hidup', NULL),
(536, NULL, 'Siap Tempur  Memenangkan Peperangan Melawan Pencobaan ', 'Mark R. Littleton ', 'Kalam Hidup', NULL),
(537, NULL, 'Siapakan Nama Sang Pencipta?', 'Samin H. Sitohang S.H., M.Div., M.Th.', 'Kalam Hidup', NULL),
(538, NULL, 'Sifat dan Karya Kristus ', 'Pdt. DR. Stephen Tong', 'Lembaga Reformed Injili Indonesia', NULL),
(539, NULL, 'Sisi Negatif dari Berpikir Positif ', 'Dave Hunt, T.A. McMahon ', 'Kalam Hidup', NULL),
(540, NULL, 'So What Gitu Loh?!', 'Mariani Sutanto ', 'Gradien Books', NULL),
(541, NULL, 'Sorga, Apa Yang Secara Pasti dapat anda ketahui mengenai kehidupan setelah kematian ', 'Charles Ferguson Ball ', 'Kalam Hidup', NULL),
(542, NULL, 'Ssstt! Jangan Katakan TIDAK! (Bimbingan Menuju Suksesnya Negosiasi) ', 'Suciati ', 'BPK -GM', NULL),
(543, NULL, 'Stand', 'John Piper', 'Pionir Jaya', NULL),
(544, NULL, 'Strategi Pelayanan SEL ', 'Pdt. Dra. Ny. P. Tuhumury, M. Div ', 'Kalam Hidup', NULL),
(545, NULL, 'Strategi Penanaman Gereja', 'Pdt. Dr. James Chang', 'Sim East Asia', NULL),
(546, NULL, 'Suami & Istri', '', 'Kalam Hidup', NULL),
(547, NULL, 'Sukacita di Dalam Kristus', 'Warren W. Wiersbe', 'Kalam Hidup', NULL),
(548, NULL, 'Surat Yakobus', '', 'LAI', NULL),
(549, NULL, 'Surat-surat Kepada Ketujuh Jemaat ', 'J. Wesley Brill ', 'Kalam Hidup', NULL),
(550, NULL, 'Surat-surat Pribadi Ilona ', 'Walter & Ingrid Trobisch', 'BPK -GM', NULL),
(551, NULL, 'Surga Itu Nyata! ', 'Daud Tony ', 'BETLEHEM ', NULL),
(552, NULL, 'Susu Ibu Paling Baik ', 'Dr. Penny & Andrew Stanway ', 'Cypress ', NULL),
(553, NULL, 'Tafsiran Ibrani', 'Dave Hagelberg, M. Th', 'Kalam Hidup', NULL),
(554, NULL, 'Tafsiran Injil Markus ', 'Walter M. Post ', 'Kalam Hidup', NULL),
(555, NULL, 'Tafsiran Injil Yohanes ', 'J. Wesley Brill ', 'Kalam Hidup', NULL),
(556, NULL, 'Tafsiran Roma Dari Bahasa Yunani', 'Dave Hagelberg, M. Th', 'Kalam Hidup', NULL),
(557, NULL, 'Tafsiran surat Filipi ', 'J. Wesley Brill ', 'Kalam Hidup', NULL),
(558, NULL, 'Tafsiran Surat Ibrani ', 'J. Wesley Brill ', 'Kalam Hidup', NULL),
(559, NULL, 'Tafsiran Surat Korintus Kedua ', 'J. Wesley Brill', 'Kalam Hidup', NULL),
(560, NULL, 'Tafsiran Surat Korintus Pertama ', 'J. Wesley Brill ', 'Kalam Hidup', NULL),
(561, NULL, 'Tafsiran Surat Tesalonika', 'J. Wesley Brill', 'Kalam Hidup', NULL),
(562, NULL, 'Tafsiran Surat Timotius & Titus', 'J. Wesley Brill', 'Kalam Hidup', NULL),
(563, NULL, 'Tafsiran Wahyu', 'James H. Conkey', 'Kalam Hidup', NULL),
(564, NULL, 'Tamu agung ', 'Jack Hayford ', 'Penerbit Gandum Mas', NULL),
(565, NULL, 'Tangan Penyertaan Tuhan', 'Antonius & Jeni Putri Tanan', 'Metanoia', NULL),
(566, NULL, 'Tangan yang Menenun', 'Mundhi Sabda H. Lesminingtyas', 'Kairos', NULL),
(567, NULL, 'Tanya Jawab Tentang Injil', '', 'bpk', NULL);
INSERT INTO `cms_lib_book` (`id`, `isbn`, `title`, `author`, `publisher`, `description`) VALUES
(568, NULL, 'Tanya Jawab tentang Injil ', '', 'BPK -GM', NULL),
(569, NULL, 'Tegar dalam Penderitaan', 'Pdt. Arliyanus Larosa', 'Kalam Hidup', NULL),
(570, NULL, 'Telaah Kritis Atas Injil Barnabas ', 'Bambang Noorsena, SH ', 'Yayasan Andi Yogyakarta', NULL),
(571, NULL, 'Temperamen Anda Dapat Diubah', 'Tim LaHaye', 'Kalam Hidup', NULL),
(572, NULL, 'Teologi Perjanjian Baru Jilid II ', 'George Eldon Ladd ', 'Kalam Hidup', NULL),
(573, NULL, 'Teologia Perjanjian Baru', 'George Eldon Ladd', 'Kalam Hidup', NULL),
(574, NULL, 'Terali Besi', 'Matia Madjiah', 'bpk', NULL),
(575, NULL, 'Terali Besi ', 'Matia Madjiah ', 'Badan Penerbit Kristen', NULL),
(576, NULL, 'Terapi Gizi untuk Penyakit Kardiovaskuler', 'DR. A. Simorangkir', 'Universal Offset', NULL),
(577, NULL, 'The Four Loves', 'C. S Lewis', 'Pionir Jaya', NULL),
(578, NULL, 'The Pilgrims''s Progress', 'John Bunyan', 'Mitra Pustaka', NULL),
(579, NULL, 'The Power of Focus', 'Daniel Ong', 'Yayasan Andi Yogyakarta', NULL),
(580, NULL, 'The Problem Of Pain', 'C. S Lewis', 'Pionir Jaya', NULL),
(581, NULL, 'The Purpose Of Christmas', 'Rick Warren', 'Pionir Jaya', NULL),
(582, NULL, 'Tiada Pengorbanan Yang Terlalu Besar: Kisah Pelayanan Ernest dan Ruth Presswood', 'Ruth Presswood Hutchins', 'Kalam Hidup', NULL),
(583, NULL, 'Tiada Tempat Tersembunyi ', 'Dorothy i. Marx', 'Penerbit Gandum Mas', NULL),
(584, NULL, 'Tidak Ada Gagang pada Salib', 'diterjemahkan: S.H. Widyapranawa, Ph. D', 'BPK -GM', NULL),
(585, NULL, 'Tidak ada Yang mustahil Bagi Allah', 'Russ Johnston & Maureen Rank', 'Yayasan Kalam Hidup', NULL),
(586, NULL, 'Tidak Lama Homo', 'Dr. William Consiglio', 'Kalam Hidup', NULL),
(587, NULL, 'Timbang Rasa: Sejumlah Artikel tentang Etiket, Keluarga dan Rumah Tangga', 'La Rose', 'Garuda Metropolitan Press', NULL),
(588, NULL, 'Tinggalkan Kutuk Terimalah Berkat ', 'Derek Prince ', 'Yayasan Pelayanan Bersama Indonesia METANOIA', NULL),
(589, NULL, 'Tjara Mengatasi Ketjemasan', 'Dr. John E. Haggai', '', NULL),
(590, NULL, 'Too Close Too Soon', 'Jim Talley & Bobbie Reed', 'Kalam Hidup', NULL),
(591, NULL, 'Totally Committed', 'Eric H. H. Chang', 'Yayasan Peduli Nusantara', NULL),
(592, NULL, 'Tugas Gereja dan Misi Masa Kini ', 'Dr. Peter Wongso ', 'seminari Alkitab Asia Tenggara ', NULL),
(593, NULL, 'Tuhah dari Poci dan Panci ', 'Eka Darmaputera ', 'BPK -GM', NULL),
(594, NULL, 'Tuhan Kita yang Menjadi Kebenaran Jahweh (I)', 'Paul C. Jong ', 'Hephzibah Publishing House ', NULL),
(595, NULL, 'Tuhan Kita yang Menjadi Kebenaran Jahweh (II)', 'Paul C. Jong ', 'Hephzibah Publishing House ', NULL),
(596, NULL, 'Tujuh Cerita Teladan (3)', '', 'Lembaga Literatur Babtis', NULL),
(597, NULL, 'Tujuh Langkah Untuk Mengatasi Masalah saudara ', 'Dr. Norman Vincent Peale', 'Yayasan Andi Yogyakarta', NULL),
(598, NULL, 'Tumbuh Semakin Kuat', 'Kenneth N. Taylor', 'Kalam Hidup', NULL),
(599, NULL, 'Uang, Seks, Dan Kekuasaan', 'Richard J. Foster', 'Kalam Hidup', NULL),
(600, NULL, 'Ujian dalam Kehidupan Orang Percaya ', 'Derek Prince ', 'Yayasan Duta Putera Mahkota ', NULL),
(601, NULL, 'Untaian Hikmat Tuhan', '', 'Metanoia', NULL),
(602, NULL, 'Untaian Mutiara Kasih ', 'Drs. Timotius Adi Tan ', 'Lembaga Literatur Babtis', NULL),
(603, NULL, 'utuh di dalam Kristus', 'Warren W. Wiersbe', 'Kalam Hidup', NULL),
(604, NULL, 'Utuh di dalam Kristus', 'Warren W. Wiersbe', 'Kalam Hidup', NULL),
(605, NULL, 'Verbum Dei', 'W. Gary Crampton', 'Momentum', NULL),
(606, NULL, 'Waktu Dan Hikmat', 'Pdt. DR. Stephen Tong', 'Lembaga Reformed Injili Indonesia', NULL),
(607, NULL, 'Waktunya Sudah Dekat', 'Charles C. Ryrie', 'Kalam Hidup', NULL),
(608, NULL, 'Wanita Bahagia ', 'Beverly LaHaye', 'Kalam Hidup', NULL),
(609, NULL, 'Wanita Idaman ', 'Diana Raya, Beverly Hendrickson', 'Kalam Hidup', NULL),
(610, NULL, 'Wanita Kristen ', 'Dr. Ruth F. Selan', 'Kalam Hidup', NULL),
(611, NULL, 'Waspadailah Diabetes-Kolestorel-Hipertensi ', 'Dr. Hans Diehl', 'Indonesia Publishing House ', NULL),
(612, NULL, 'Watak Orang Kristen', '', 'Kalam Hidup', NULL),
(613, NULL, 'Watak Pekerja Kristus', 'Tom Yeakley', 'Yayasan Kalam Hidup', NULL),
(614, NULL, 'When Dreams come true', 'Eric dan Leslie Ludy', 'Gloria Graffa', NULL),
(615, NULL, 'Yakin Di Dalam Kristus', 'Warren W. Wiersbe', 'Yayasan Kalam Hidup', NULL),
(616, NULL, 'Yesus Kristus Pengudus Kita', 'A.B. Simpson', 'Gandum Mas', NULL);
