<?php defined('BASEPATH') OR exit('No direct script access allowed');
// GENERATED AUTOMATICALLY, DO NOT EDIT THIS FILE !!!
// Is the theme published for every subsite?
$public = FALSE;
$subsite_allowed = array();
