<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');
/**
 * Installation script for breast_cancer
 *
 * @author No-CMS Module Generator
 */
class Install extends CMS_Module_Installer {
    /////////////////////////////////////////////////////////////////////////////
    // Default Variables
    /////////////////////////////////////////////////////////////////////////////

    protected $DEPENDENCIES = array();
    protected $NAME         = 'admin.breast_cancer';
    protected $DESCRIPTION  = 'Another cool module generated by Nordrassil ...';
    protected $VERSION      = '0.0.0';

    public function cms_complete_table_name($table_name){
        $this->load->helper($this->cms_module_path().'/function');
        if(function_exists('cms_complete_table_name')){
            return cms_complete_table_name($table_name);
        }else{
            return parent::cms_complete_table_name($table_name);
        }
    }


    /////////////////////////////////////////////////////////////////////////////
    // Default Functions
    /////////////////////////////////////////////////////////////////////////////

    // ACTIVATION
    protected function do_activate(){
        $this->remove_all();
        $this->build_all();
    }

    // DEACTIVATION
    protected function do_deactivate(){
        $this->backup_database(array(
            $this->cms_complete_table_name('pasien')
        ));
        $this->remove_all();
    }

    // UPGRADE
    protected function do_upgrade($old_version){
        // Add your migration logic here.
    }

    // OVERRIDE THIS FUNCTION TO PROVIDE "Module Setting" FEATURE
    public function setting(){
        $module_directory = $this->cms_module_path();
        $data = array();
        $data['IS_ACTIVE'] = $this->IS_ACTIVE;
        $data['module_directory'] = $module_directory;
        if(!$this->IS_ACTIVE){
            // get setting
            $module_table_prefix = $this->input->post('module_table_prefix');
            $module_prefix       = $this->input->post('module_prefix');
            // set values
            if(isset($module_table_prefix) && $module_table_prefix !== FALSE){
                cms_module_config($module_directory, 'module_table_prefix', $module_table_prefix);
            }
            if(isset($module_prefix) && $module_prefix !== FALSE){
                cms_module_prefix($module_directory, $module_prefix);
            }
            // get values
            $data['module_table_prefix'] = cms_module_config($module_directory, 'module_table_prefix');
            $data['module_prefix']       = cms_module_prefix($module_directory);
        }
        $this->view($module_directory.'/install_setting', $data, 'main_module_management');
    }

    /////////////////////////////////////////////////////////////////////////////
    // Private Functions
    /////////////////////////////////////////////////////////////////////////////

    // REMOVE ALL NAVIGATIONS, WIDGETS, AND PRIVILEGES
    private function remove_all(){
        $module_path = $this->cms_module_path();

        // remove navigations
        $this->remove_navigation($this->cms_complete_navigation_name('manage_pasien'));


        // remove parent of all navigations
        $this->remove_navigation($this->cms_complete_navigation_name('index'));

        // drop tables
        $this->dbforge->drop_table($this->cms_complete_table_name('pasien'), TRUE);
    }

    // CREATE ALL NAVIGATIONS, WIDGETS, AND PRIVILEGES
    private function build_all(){
        $module_path = $this->cms_module_path();

        // parent of all navigations
        $this->add_navigation($this->cms_complete_navigation_name('index'), 'Breast Cancer',
            $module_path.'/breast_cancer', $this->PRIV_EVERYONE);

        // add navigations
        $this->add_navigation($this->cms_complete_navigation_name('manage_pasien'), 'Manage Pasien',
            $module_path.'/manage_pasien', $this->PRIV_AUTHORIZED, $this->cms_complete_navigation_name('index')
        );


        // create tables
        // pasien
        $fields = array(
            'id'=> $this->TYPE_INT_UNSIGNED_AUTO_INCREMENT,
            'nama_lengkap'=> array("type"=>'varchar', "constraint"=>100, "null"=>TRUE),
            'nama_panggilan'=> array("type"=>'varchar', "constraint"=>45, "null"=>TRUE),
            'foto'=> array("type"=>'varchar', "constraint"=>255, "null"=>TRUE),
            'alamat'=> array("type"=>'varchar', "constraint"=>100, "null"=>TRUE),
            'telepon'=> array("type"=>'varchar', "constraint"=>45, "null"=>TRUE),
            'hp'=> array("type"=>'varchar', "constraint"=>45, "null"=>TRUE),
            'pin_bbm'=> array("type"=>'varchar', "constraint"=>45, "null"=>TRUE),
            'email'=> array("type"=>'varchar', "constraint"=>45, "null"=>TRUE),
            'tanggal_lahir'=> array("type"=>'date', "null"=>TRUE),
            'tempat_lahir'=> array("type"=>'varchar', "constraint"=>45, "null"=>TRUE),
            'usia'=> array("type"=>'int', "constraint"=>10, "null"=>TRUE),
            'berat_badan'=> array("type"=>'float', "null"=>TRUE),
            'tinggi_badan'=> array("type"=>'float', "null"=>TRUE),
            'kelainan_fisik'=> array("type"=>'text', "null"=>TRUE),
            'golongan_darah'=> array("type"=>'enum', "constraint"=>array('A','AB','B','O'), "null"=>TRUE),
            'jumlah_anak'=> array("type"=>'int', "constraint"=>10, "null"=>TRUE),
            'menyusui'=> array("type"=>'int', "constraint"=>10, "null"=>TRUE),
            'lama_menyusui'=> array("type"=>'int', "constraint"=>10, "null"=>TRUE),
            'nenek_kanker'=> array("type"=>'int', "constraint"=>10, "null"=>TRUE),
            'umur_diagnosa_nenek_kanker'=> array("type"=>'int', "constraint"=>10, "null"=>TRUE),
            'ibu_kanker'=> array("type"=>'int', "constraint"=>10, "null"=>TRUE),
            'umur_diagnosa_ibu_kanker'=> array("type"=>'int', "constraint"=>10, "null"=>TRUE),
            'bibi_kanker'=> array("type"=>'int', "constraint"=>10, "null"=>TRUE),
            'umur_diagnosa_bibi_kanker'=> array("type"=>'int', "constraint"=>10, "null"=>TRUE),
            'saudara_kanker'=> array("type"=>'int', "constraint"=>10, "null"=>TRUE),
            'umur_diagnosa_saudara_kanker'=> array("type"=>'int', "constraint"=>10, "null"=>TRUE),
            'kemenakan_kanker'=> array("type"=>'int', "constraint"=>10, "null"=>TRUE),
            'umur_diagnosa_kemenakan_kanker'=> array("type"=>'int', "constraint"=>10, "null"=>TRUE),
            'anak_kanker'=> array("type"=>'int', "constraint"=>10, "null"=>TRUE),
            'umur_diagnosa_anak_kanker'=> array("type"=>'varchar', "constraint"=>45, "null"=>TRUE),
            'sakit'=> array("type"=>'int', "constraint"=>10, "null"=>TRUE),
            'lama_sakit'=> array("type"=>'int', "constraint"=>10, "null"=>TRUE),
            'penemu_sakit'=> array("type"=>'varchar', "constraint"=>45, "null"=>TRUE),
            'benjolan'=> array("type"=>'int', "constraint"=>10, "null"=>TRUE),
            'lama_benjolan'=> array("type"=>'int', "constraint"=>10, "null"=>TRUE),
            'penemu_benjolan'=> array("type"=>'varchar', "constraint"=>45, "null"=>TRUE),
            'pengerasan'=> array("type"=>'int', "constraint"=>10, "null"=>TRUE),
            'lama_pengerasan'=> array("type"=>'int', "constraint"=>10, "null"=>TRUE),
            'penemu_pengerasan'=> array("type"=>'varchar', "constraint"=>45, "null"=>TRUE),
            'kategori'=> array("type"=>'enum', "constraint"=>array('A1','A2','B1','B2','C'), "null"=>TRUE)
        );
        $this->dbforge->add_field($fields);
        $this->dbforge->add_key('id', TRUE);
        $this->dbforge->create_table($this->cms_complete_table_name('pasien'));


    }

    // EXPORT DATABASE
    private function backup_database($table_names, $limit = 100){
        if($this->db->platform() == 'mysql' || $this->db->platform() == 'mysqli'){
            $module_path = $this->cms_module_path();
            $this->load->dbutil();
            $sql = '';

            // create DROP TABLE syntax
            for($i=count($table_names)-1; $i>=0; $i--){
                $table_name = $table_names[$i];
                $sql .= 'DROP TABLE IF EXISTS `'.$table_name.'`; '.PHP_EOL;
            }
            if($sql !='')$sql.= PHP_EOL;

            // create CREATE TABLE and INSERT syntax

            $prefs = array(
                    'tables'      => $table_names,
                    'ignore'      => array(),
                    'format'      => 'txt',
                    'filename'    => 'mybackup.sql',
                    'add_drop'    => FALSE,
                    'add_insert'  => TRUE,
                    'newline'     => PHP_EOL
                  );
            $sql.= @$this->dbutil->backup($prefs);

            //write file
            chmod(FCPATH.'modules/'.$module_path.'/assets/db/', 0777);
            $file_name = 'backup_'.date('Y-m-d_G-i-s').'.sql';
            file_put_contents(
                    FCPATH.'modules/'.$module_path.'/assets/db/'.$file_name,
                    $sql
                );
        }

    }
}
