<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');
/**
 * Installation script for stiki_ibk
 *
 * @author No-CMS Module Generator
 */
class Install extends CMS_Module_Installer {
    /////////////////////////////////////////////////////////////////////////////
    // Default Variables
    /////////////////////////////////////////////////////////////////////////////

    protected $DEPENDENCIES = array();
    protected $NAME         = 'admin.stiki_ibk';
    protected $DESCRIPTION  = 'Another cool module generated by Nordrassil ...';
    protected $VERSION      = '0.0.0';


    /////////////////////////////////////////////////////////////////////////////
    // Default Functions
    /////////////////////////////////////////////////////////////////////////////

    // ACTIVATION
    protected function do_activate(){
        $this->remove_all();
        $this->build_all();
    }

    // DEACTIVATION
    protected function do_deactivate(){
        $this->backup_database(array(
            $this->cms_complete_table_name('anggota_lomba'),
            $this->cms_complete_table_name('dosen'),
            $this->cms_complete_table_name('jenis_lomba'),
            $this->cms_complete_table_name('lomba'),
            $this->cms_complete_table_name('mahasiswa'),
            $this->cms_complete_table_name('seminar'),
            $this->cms_complete_table_name('status_bayar')
        ));
        $this->remove_all();
    }

    // UPGRADE
    protected function do_upgrade($old_version){
        // Add your migration logic here.
    }

    // OVERRIDE THIS FUNCTION TO PROVIDE "Module Setting" FEATURE
    public function setting(){
        $module_directory = $this->cms_module_path();
        $data = array();
        $data['IS_ACTIVE'] = $this->IS_ACTIVE;
        $data['module_directory'] = $module_directory;
        if(!$this->IS_ACTIVE){
            // get setting
            $module_table_prefix = $this->input->post('module_table_prefix');
            $module_prefix       = $this->input->post('module_prefix');
            // set values
            if(isset($module_table_prefix) && $module_table_prefix !== FALSE){
                cms_module_config($module_directory, 'module_table_prefix', $module_table_prefix);
            }
            if(isset($module_prefix) && $module_prefix !== FALSE){
                cms_module_prefix($module_directory, $module_prefix);
            }
            // get values
            $data['module_table_prefix'] = cms_module_config($module_directory, 'module_table_prefix');
            $data['module_prefix']       = cms_module_prefix($module_directory);
        }
        $this->view($module_directory.'/install_setting', $data, 'main_module_management');
    }

    /////////////////////////////////////////////////////////////////////////////
    // Private Functions
    /////////////////////////////////////////////////////////////////////////////

    // REMOVE ALL NAVIGATIONS, WIDGETS, AND PRIVILEGES
    private function remove_all(){
        $module_path = $this->cms_module_path();

        // remove navigations
        $this->remove_navigation($this->cms_complete_navigation_name('manage_seminar'));
        $this->remove_navigation($this->cms_complete_navigation_name('manage_mahasiswa'));
        $this->remove_navigation($this->cms_complete_navigation_name('manage_lomba'));
        $this->remove_navigation($this->cms_complete_navigation_name('manage_jenis_lomba'));
        $this->remove_navigation($this->cms_complete_navigation_name('manage_dosen'));


        // remove parent of all navigations
        $this->remove_navigation($this->cms_complete_navigation_name('index'));
        
        // drop tables
        $this->dbforge->drop_table($this->cms_complete_table_name('status_bayar'), TRUE);
        $this->dbforge->drop_table($this->cms_complete_table_name('seminar'), TRUE);
        $this->dbforge->drop_table($this->cms_complete_table_name('mahasiswa'), TRUE);
        $this->dbforge->drop_table($this->cms_complete_table_name('lomba'), TRUE);
        $this->dbforge->drop_table($this->cms_complete_table_name('jenis_lomba'), TRUE);
        $this->dbforge->drop_table($this->cms_complete_table_name('dosen'), TRUE);
        $this->dbforge->drop_table($this->cms_complete_table_name('anggota_lomba'), TRUE);
    }

    // CREATE ALL NAVIGATIONS, WIDGETS, AND PRIVILEGES
    private function build_all(){
        $module_path = $this->cms_module_path();

        // parent of all navigations
        $this->add_navigation($this->cms_complete_navigation_name('index'), 'Pendaftaran IBK',
            $module_path.'/stiki_ibk', $this->PRIV_EVERYONE);

        // add navigations
        $this->add_navigation($this->cms_complete_navigation_name('manage_dosen'), 'Manage Dosen',
            $module_path.'/manage_dosen', $this->PRIV_AUTHORIZED, $this->cms_complete_navigation_name('index')
        );        
        $this->add_navigation($this->cms_complete_navigation_name('manage_mahasiswa'), 'Manage Mahasiswa',
            $module_path.'/manage_mahasiswa', $this->PRIV_AUTHORIZED, $this->cms_complete_navigation_name('index')
        );
        $this->add_navigation($this->cms_complete_navigation_name('manage_jenis_lomba'), 'Manage Jenis Lomba',
            $module_path.'/manage_jenis_lomba', $this->PRIV_AUTHORIZED, $this->cms_complete_navigation_name('index')
        );
        $this->add_navigation($this->cms_complete_navigation_name('manage_lomba'), 'Pendaftaran Lomba',
            $module_path.'/manage_lomba', $this->PRIV_AUTHORIZED, $this->cms_complete_navigation_name('index')
        );
        $this->add_navigation($this->cms_complete_navigation_name('manage_seminar'), 'Pendaftaran Seminar',
            $module_path.'/manage_seminar', $this->PRIV_AUTHORIZED, $this->cms_complete_navigation_name('index')
        );

        
        // create tables
        // anggota_lomba
        $fields = array(
            'id'=> $this->TYPE_INT_UNSIGNED_AUTO_INCREMENT,
            'id_lomba'=> array("type"=>'int', "constraint"=>10, "null"=>TRUE),
            'id_mahasiswa'=> array("type"=>'int', "constraint"=>10, "null"=>TRUE)
        );
        $this->dbforge->add_field($fields);
        $this->dbforge->add_key('id', TRUE);
        $this->dbforge->create_table($this->cms_complete_table_name('anggota_lomba'));

        // dosen
        $fields = array(
            'id'=> $this->TYPE_INT_UNSIGNED_AUTO_INCREMENT,
            'nidn'=> array("type"=>'varchar', "constraint"=>20, "null"=>TRUE),
            'nama'=> array("type"=>'varchar', "constraint"=>50, "null"=>TRUE)
        );
        $this->dbforge->add_field($fields);
        $this->dbforge->add_key('id', TRUE);
        $this->dbforge->create_table($this->cms_complete_table_name('dosen'));

        // jenis_lomba
        $fields = array(
            'id'=> $this->TYPE_INT_UNSIGNED_AUTO_INCREMENT,
            'nama'=> array("type"=>'varchar', "constraint"=>50, "null"=>TRUE)
        );
        $this->dbforge->add_field($fields);
        $this->dbforge->add_key('id', TRUE);
        $this->dbforge->create_table($this->cms_complete_table_name('jenis_lomba'));

        // insert default jenis lomba
        $table_name = $this->cms_complete_table_name('jenis_lomba');
        $this->db->insert($table_name, array('nama'=>'Karsa Cipta'));
        $this->db->insert($table_name, array('nama'=>'Penerapan Teknologi'));
        $this->db->insert($table_name, array('nama'=>'Pengabdian Masyarakat'));
        $this->db->insert($table_name, array('nama'=>'Kewirausahaan'));
        $this->db->insert($table_name, array('nama'=>'Gagasan Tertulis'));

        // lomba
        $fields = array(
            'id'=> $this->TYPE_INT_UNSIGNED_AUTO_INCREMENT,
            'judul'=> array("type"=>'varchar', "constraint"=>100, "null"=>TRUE),
            'id_jenis_lomba'=> array("type"=>'int', "constraint"=>10, "null"=>TRUE),
            'id_mahasiswa_ketua'=> array("type"=>'int', "constraint"=>10, "null"=>TRUE),
            'id_dosen_pembimbing'=> array("type"=>'int', "constraint"=>10, "null"=>TRUE),
            'proposal'=> array("type"=>'varchar', "constraint"=>100, "null"=>TRUE),
            'id_user'=> array("type"=>'int', "constraint"=>10, "null"=>TRUE),
            'anggota'=> array("type"=>'varchar', "constraint"=>255, "null"=>TRUE)
        );
        $this->dbforge->add_field($fields);
        $this->dbforge->add_key('id', TRUE);
        $this->dbforge->create_table($this->cms_complete_table_name('lomba'));

        // mahasiswa
        $fields = array(
            'id'=> $this->TYPE_INT_UNSIGNED_AUTO_INCREMENT,
            'nrp'=> array("type"=>'varchar', "constraint"=>20, "null"=>TRUE),
            'nama'=> array("type"=>'varchar', "constraint"=>100, "null"=>TRUE)
        );
        $this->dbforge->add_field($fields);
        $this->dbforge->add_key('id', TRUE);
        $this->dbforge->create_table($this->cms_complete_table_name('mahasiswa'));

        // seminar
        $fields = array(
            'id'=> $this->TYPE_INT_UNSIGNED_AUTO_INCREMENT,
            'id_user'=> array("type"=>'int', "constraint"=>10, "null"=>TRUE),
            'id_mahasiswa'=> array("type"=>'int', "constraint"=>10, "null"=>TRUE),
            'alamat'=> array("type"=>'varchar', "constraint"=>100, "null"=>TRUE),
            'email'=> array("type"=>'varchar', "constraint"=>100, "null"=>TRUE),
            'telepon'=> array("type"=>'varchar', "constraint"=>20, "null"=>TRUE),
            'id_status_bayar'=> array("type"=>'int', "constraint"=>10, "null"=>TRUE),
            'keterangan_status_bayar'=> array("type"=>'varchar', "constraint"=>100, "null"=>TRUE)
        );
        $this->dbforge->add_field($fields);
        $this->dbforge->add_key('id', TRUE);
        $this->dbforge->create_table($this->cms_complete_table_name('seminar'));

        // status_bayar
        $fields = array(
            'id'=> $this->TYPE_INT_UNSIGNED_AUTO_INCREMENT,
            'nama'=> array("type"=>'varchar', "constraint"=>50, "null"=>TRUE)
        );
        $this->dbforge->add_field($fields);
        $this->dbforge->add_key('id', TRUE);
        $this->dbforge->create_table($this->cms_complete_table_name('status_bayar'));

        // insert default status pembayaran
        $table_name = $this->cms_complete_table_name('status_bayar');
        $this->db->insert($table_name, array('id'=>1, 'nama'=>'Lunas'));
        $this->db->insert($table_name, array('id'=>2, 'nama'=>'Belum Lunas'));
        $this->db->insert($table_name, array('id'=>3, 'nama'=>'Lain-Lain'));

        
    }

    // EXPORT DATABASE
    private function backup_database($table_names, $limit = 100){         
        if($this->db->platform() == 'mysql' || $this->db->platform() == 'mysqli'){
            $module_path = $this->cms_module_path();
            $this->load->dbutil();
            $sql = '';
            
            // create DROP TABLE syntax
            for($i=count($table_names)-1; $i>=0; $i--){
                $table_name = $table_names[$i];
                $sql .= 'DROP TABLE IF EXISTS `'.$table_name.'`; '.PHP_EOL;
            }
            if($sql !='')$sql.= PHP_EOL;

            // create CREATE TABLE and INSERT syntax 
            
            $prefs = array(
                    'tables'      => $table_names,
                    'ignore'      => array(),
                    'format'      => 'txt',
                    'filename'    => 'mybackup.sql',
                    'add_drop'    => FALSE,
                    'add_insert'  => TRUE,
                    'newline'     => PHP_EOL
                  );
            $sql.= @$this->dbutil->backup($prefs);        

            //write file
            $file_name = 'backup_'.date('Y-m-d_G:i:s').'.sql';
            file_put_contents(
                    BASEPATH.'../modules/'.$module_path.'/assets/db/'.$file_name,
                    $sql
                );
        }       

    }
}
